/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI;

import PropertyMeld.MeldAPI.utils.HTTPClient;
import PropertyMeld.MeldAPI.utils.HTTPRequest;
import PropertyMeld.MeldAPI.utils.JSON;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import org.apache.http.NameValuePair;

public class Schema {
	
	private SDKConfiguration sdkConfiguration;

	public Schema(SDKConfiguration sdkConfiguration) {
		this.sdkConfiguration = sdkConfiguration;
	}

    /**
     * OpenApi3 schema for this API. Format can be selected via content negotiation. -  - - YAML: application/vnd.oai.openapi - - JSON: application/vnd.oai.openapi+json
     * @param request the request object containing all of the parameters for the API call
     * @param security the security details to use for authentication
     * @return the response from the API call
     * @throws Exception if the API call fails
     */
    public PropertyMeld.MeldAPI.models.operations.SchemaRetrieveResponse schemaRetrieve(PropertyMeld.MeldAPI.models.operations.SchemaRetrieveRequest request, PropertyMeld.MeldAPI.models.operations.SchemaRetrieveSecurity security) throws Exception {
        String baseUrl = this.sdkConfiguration.serverUrl;
        String url = PropertyMeld.MeldAPI.utils.Utils.generateURL(baseUrl, "/api/v0.0.1/schema/");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);

        req.addHeader("Accept", "application/json;q=1, application/vnd.oai.openapi+json;q=0.8, application/yaml;q=0.5, application/vnd.oai.openapi;q=0");
        req.addHeader("user-agent", String.format("speakeasy-sdk/%s %s %s %s", this.sdkConfiguration.language, this.sdkConfiguration.sdkVersion, this.sdkConfiguration.genVersion, this.sdkConfiguration.openapiDocVersion));
        java.util.List<NameValuePair> queryParams = PropertyMeld.MeldAPI.utils.Utils.getQueryParams(PropertyMeld.MeldAPI.models.operations.SchemaRetrieveRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        java.util.Map<String, java.util.List<String>> headers = PropertyMeld.MeldAPI.utils.Utils.getHeaders(request);
        if (headers != null) {
            for (java.util.Map.Entry<String, java.util.List<String>> header : headers.entrySet()) {
                for (String value : header.getValue()) {
                    req.addHeader(header.getKey(), value);
                }
            }
        }
        
        HTTPClient client = PropertyMeld.MeldAPI.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, security);
        
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        PropertyMeld.MeldAPI.models.operations.SchemaRetrieveResponse res = new PropertyMeld.MeldAPI.models.operations.SchemaRetrieveResponse(contentType, httpRes.statusCode()) {{
            schemaRetrieve200ApplicationJSONObject = null;
            body = null;
            body = null;
            schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (PropertyMeld.MeldAPI.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                java.util.Map<String, Object> out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), new TypeReference<java.util.Map<String, Object>>() {});
                res.schemaRetrieve200ApplicationJSONObject = out;
            }
            if (PropertyMeld.MeldAPI.utils.Utils.matchContentType(contentType, "application/vnd.oai.openapi")) {
                byte[] out = httpRes.body();
                res.body = out;
            }
            if (PropertyMeld.MeldAPI.utils.Utils.matchContentType(contentType, "application/yaml")) {
                byte[] out = httpRes.body();
                res.body = out;
            }
            if (PropertyMeld.MeldAPI.utils.Utils.matchContentType(contentType, "application/vnd.oai.openapi+json")) {
                ObjectMapper mapper = JSON.getMapper();
                java.util.Map<String, Object> out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), new TypeReference<java.util.Map<String, Object>>() {});
                res.schemaRetrieve200ApplicationVndOaiOpenapiPlusJsonObject = out;
            }
        }

        return res;
    }
}