/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class CheckTokenRetrieveResponse {
    
    public String contentType;

    public CheckTokenRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public CheckTokenRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CheckTokenRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    
    public java.util.Map<String, Object> checkTokenRetrieve200ApplicationJSONObject;

    public CheckTokenRetrieveResponse withCheckTokenRetrieve200ApplicationJSONObject(java.util.Map<String, Object> checkTokenRetrieve200ApplicationJSONObject) {
        this.checkTokenRetrieve200ApplicationJSONObject = checkTokenRetrieve200ApplicationJSONObject;
        return this;
    }
    
    public CheckTokenRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
