/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ExpenditureRetrieveResponse {
    
    public String contentType;

    public ExpenditureRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.MeldExpendituresListViewSerializerDetail meldExpendituresListViewSerializerDetail;

    public ExpenditureRetrieveResponse withMeldExpendituresListViewSerializerDetail(PropertyMeld.MeldAPI.models.shared.MeldExpendituresListViewSerializerDetail meldExpendituresListViewSerializerDetail) {
        this.meldExpendituresListViewSerializerDetail = meldExpendituresListViewSerializerDetail;
        return this;
    }
    
    
    public Integer statusCode;

    public ExpenditureRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ExpenditureRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ExpenditureRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
