/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ExpenditureListStatus {
    APPROVED("APPROVED"),
    BILLED("BILLED"),
    DRAFT("DRAFT"),
    HOLD("HOLD"),
    IN_REVIEW("IN_REVIEW");

    @JsonValue
    public final String value;

    private ExpenditureListStatus(String value) {
        this.value = value;
    }
}
