/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

public class ExpenditureListRequest {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Pm-Org")
    public Long xPmOrg;

    public ExpenditureListRequest withXPmOrg(Long xPmOrg) {
        this.xPmOrg = xPmOrg;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__gte")
    public OffsetDateTime createdGte;

    public ExpenditureListRequest withCreatedGte(OffsetDateTime createdGte) {
        this.createdGte = createdGte;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__interval")
    public OffsetDateTime createdInterval;

    public ExpenditureListRequest withCreatedInterval(OffsetDateTime createdInterval) {
        this.createdInterval = createdInterval;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__lte")
    public OffsetDateTime createdLte;

    public ExpenditureListRequest withCreatedLte(OffsetDateTime createdLte) {
        this.createdLte = createdLte;
        return this;
    }
    
    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public ExpenditureListRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public Long offset;

    public ExpenditureListRequest withOffset(Long offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * Which field to use when ordering the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ordering")
    public String ordering;

    public ExpenditureListRequest withOrdering(String ordering) {
        this.ordering = ordering;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")
    public ExpenditureListStatus[] status;

    public ExpenditureListRequest withStatus(ExpenditureListStatus[] status) {
        this.status = status;
        return this;
    }
    
    public ExpenditureListRequest(@JsonProperty("X-Pm-Org") Long xPmOrg) {
        this.xPmOrg = xPmOrg;
  }
}
