/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ExpenditureListResponse {
    
    public String contentType;

    public ExpenditureListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedMeldExpendituresListViewSerializerListList paginatedMeldExpendituresListViewSerializerListList;

    public ExpenditureListResponse withPaginatedMeldExpendituresListViewSerializerListList(PropertyMeld.MeldAPI.models.shared.PaginatedMeldExpendituresListViewSerializerListList paginatedMeldExpendituresListViewSerializerListList) {
        this.paginatedMeldExpendituresListViewSerializerListList = paginatedMeldExpendituresListViewSerializerListList;
        return this;
    }
    
    
    public Integer statusCode;

    public ExpenditureListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ExpenditureListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ExpenditureListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
