/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class FloorRetrieveResponse {
    
    public String contentType;

    public FloorRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.FloorSerializerDetail floorSerializerDetail;

    public FloorRetrieveResponse withFloorSerializerDetail(PropertyMeld.MeldAPI.models.shared.FloorSerializerDetail floorSerializerDetail) {
        this.floorSerializerDetail = floorSerializerDetail;
        return this;
    }
    
    
    public Integer statusCode;

    public FloorRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FloorRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public FloorRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
