/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class FloorListResponse {
    
    public String contentType;

    public FloorListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedFloorSerializerListList paginatedFloorSerializerListList;

    public FloorListResponse withPaginatedFloorSerializerListList(PropertyMeld.MeldAPI.models.shared.PaginatedFloorSerializerListList paginatedFloorSerializerListList) {
        this.paginatedFloorSerializerListList = paginatedFloorSerializerListList;
        return this;
    }
    
    
    public Integer statusCode;

    public FloorListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FloorListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public FloorListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
