/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class InvoiceListRequest {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Pm-Org")
    public Long xPmOrg;

    public InvoiceListRequest withXPmOrg(Long xPmOrg) {
        this.xPmOrg = xPmOrg;
        return this;
    }
    
    /**
     * created__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__gte")
    public String createdGte;

    public InvoiceListRequest withCreatedGte(String createdGte) {
        this.createdGte = createdGte;
        return this;
    }
    
    /**
     * created__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__interval")
    public String createdInterval;

    public InvoiceListRequest withCreatedInterval(String createdInterval) {
        this.createdInterval = createdInterval;
        return this;
    }
    
    /**
     * created__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__lte")
    public String createdLte;

    public InvoiceListRequest withCreatedLte(String createdLte) {
        this.createdLte = createdLte;
        return this;
    }
    
    /**
     * declined
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=declined")
    public InvoiceListDeclined declined;

    public InvoiceListRequest withDeclined(InvoiceListDeclined declined) {
        this.declined = declined;
        return this;
    }
    
    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public InvoiceListRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public Long offset;

    public InvoiceListRequest withOffset(Long offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * Which field to use when ordering the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ordering")
    public String ordering;

    public InvoiceListRequest withOrdering(String ordering) {
        this.ordering = ordering;
        return this;
    }
    
    /**
     * paid
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=paid")
    public InvoiceListPaid paid;

    public InvoiceListRequest withPaid(InvoiceListPaid paid) {
        this.paid = paid;
        return this;
    }
    
    /**
     * payment_requested__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=payment_requested__gte")
    public String paymentRequestedGte;

    public InvoiceListRequest withPaymentRequestedGte(String paymentRequestedGte) {
        this.paymentRequestedGte = paymentRequestedGte;
        return this;
    }
    
    /**
     * payment_requested__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=payment_requested__interval")
    public String paymentRequestedInterval;

    public InvoiceListRequest withPaymentRequestedInterval(String paymentRequestedInterval) {
        this.paymentRequestedInterval = paymentRequestedInterval;
        return this;
    }
    
    /**
     * payment_requested__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=payment_requested__lte")
    public String paymentRequestedLte;

    public InvoiceListRequest withPaymentRequestedLte(String paymentRequestedLte) {
        this.paymentRequestedLte = paymentRequestedLte;
        return this;
    }
    
    /**
     * status
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")
    public InvoiceListStatus status;

    public InvoiceListRequest withStatus(InvoiceListStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * vendor
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=vendor")
    public String vendor;

    public InvoiceListRequest withVendor(String vendor) {
        this.vendor = vendor;
        return this;
    }
    
    /**
     * vendors
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=vendors")
    public String vendors;

    public InvoiceListRequest withVendors(String vendors) {
        this.vendors = vendors;
        return this;
    }
    
    public InvoiceListRequest(@JsonProperty("X-Pm-Org") Long xPmOrg) {
        this.xPmOrg = xPmOrg;
  }
}
