/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InvoiceListStatus - status
 */
public enum InvoiceListStatus {
    DRAFT("DRAFT"),
    SUBMITTED("SUBMITTED"),
    IN_REVIEW("IN_REVIEW"),
    HOLD("HOLD"),
    DECLINED("DECLINED"),
    APPROVED("APPROVED"),
    PAID("PAID");

    @JsonValue
    public final String value;

    private InvoiceListStatus(String value) {
        this.value = value;
    }
}
