/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ManagementAgentListResponse {
    
    public String contentType;

    public ManagementAgentListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedManagementAgentSerializerListList paginatedManagementAgentSerializerListList;

    public ManagementAgentListResponse withPaginatedManagementAgentSerializerListList(PropertyMeld.MeldAPI.models.shared.PaginatedManagementAgentSerializerListList paginatedManagementAgentSerializerListList) {
        this.paginatedManagementAgentSerializerListList = paginatedManagementAgentSerializerListList;
        return this;
    }
    
    
    public Integer statusCode;

    public ManagementAgentListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ManagementAgentListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ManagementAgentListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
