/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ManagementAgentRetrieveResponse {
    
    public String contentType;

    public ManagementAgentRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.ManagementAgentSerializerDetail managementAgentSerializerDetail;

    public ManagementAgentRetrieveResponse withManagementAgentSerializerDetail(PropertyMeld.MeldAPI.models.shared.ManagementAgentSerializerDetail managementAgentSerializerDetail) {
        this.managementAgentSerializerDetail = managementAgentSerializerDetail;
        return this;
    }
    
    
    public Integer statusCode;

    public ManagementAgentRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ManagementAgentRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ManagementAgentRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
