/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MeldListRecurring - recurring
 */
public enum MeldListRecurring {
    TRUE("true"),
    FALSE("false");

    @JsonValue
    public final String value;

    private MeldListRecurring(String value) {
        this.value = value;
    }
}
