/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class MeldTenantFilesListResponse {
    
    public String contentType;

    public MeldTenantFilesListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedPmAPITenantMeldList paginatedPmAPITenantMeldList;

    public MeldTenantFilesListResponse withPaginatedPmAPITenantMeldList(PropertyMeld.MeldAPI.models.shared.PaginatedPmAPITenantMeldList paginatedPmAPITenantMeldList) {
        this.paginatedPmAPITenantMeldList = paginatedPmAPITenantMeldList;
        return this;
    }
    
    
    public Integer statusCode;

    public MeldTenantFilesListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public MeldTenantFilesListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public MeldTenantFilesListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
