/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class MeldRetrieveResponse {
    
    public String contentType;

    public MeldRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.MeldSerializerDetailOutput meldSerializerDetail;

    public MeldRetrieveResponse withMeldSerializerDetail(PropertyMeld.MeldAPI.models.shared.MeldSerializerDetailOutput meldSerializerDetail) {
        this.meldSerializerDetail = meldSerializerDetail;
        return this;
    }
    
    
    public Integer statusCode;

    public MeldRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public MeldRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public MeldRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
