/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class MeldListResponse {
    
    public String contentType;

    public MeldListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedMeldSerializerListList paginatedMeldSerializerListList;

    public MeldListResponse withPaginatedMeldSerializerListList(PropertyMeld.MeldAPI.models.shared.PaginatedMeldSerializerListList paginatedMeldSerializerListList) {
        this.paginatedMeldSerializerListList = paginatedMeldSerializerListList;
        return this;
    }
    
    
    public Integer statusCode;

    public MeldListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public MeldListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public MeldListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
