/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MeldListMaintType - maint_type
 */
public enum MeldListMaintType {
    ONE("1"),
    TWO("2");

    @JsonValue
    public final String value;

    private MeldListMaintType(String value) {
        this.value = value;
    }
}
