/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MeldListOwnerApproval - owner_approval
 */
public enum MeldListOwnerApproval {
    OWNER_APPROVAL_NOT_REQUESTED("OWNER_APPROVAL_NOT_REQUESTED"),
    OWNER_APPROVAL_REQUESTED("OWNER_APPROVAL_REQUESTED"),
    OWNER_APPROVAL_APPROVED("OWNER_APPROVAL_APPROVED"),
    OWNER_APPROVAL_NOT_APPROVED("OWNER_APPROVAL_NOT_APPROVED"),
    OWNER_APPROVAL_REQUESTED_ESTIMATES("OWNER_APPROVAL_REQUESTED_ESTIMATES");

    @JsonValue
    public final String value;

    private MeldListOwnerApproval(String value) {
        this.value = value;
    }
}
