/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class MeldVendorFilesListResponse {
    
    public String contentType;

    public MeldVendorFilesListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedPMApiVendorMeldFileList paginatedPMApiVendorMeldFileList;

    public MeldVendorFilesListResponse withPaginatedPMApiVendorMeldFileList(PropertyMeld.MeldAPI.models.shared.PaginatedPMApiVendorMeldFileList paginatedPMApiVendorMeldFileList) {
        this.paginatedPMApiVendorMeldFileList = paginatedPMApiVendorMeldFileList;
        return this;
    }
    
    
    public Integer statusCode;

    public MeldVendorFilesListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public MeldVendorFilesListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public MeldVendorFilesListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
