/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class MeldListRequest {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Pm-Org")
    public Long xPmOrg;

    public MeldListRequest withXPmOrg(Long xPmOrg) {
        this.xPmOrg = xPmOrg;
        return this;
    }
    
    /**
     * ack_approval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ack_approval")
    public MeldListAckApproval ackApproval;

    public MeldListRequest withAckApproval(MeldListAckApproval ackApproval) {
        this.ackApproval = ackApproval;
        return this;
    }
    
    /**
     * assigned_to_me
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=assigned_to_me")
    public String assignedToMe;

    public MeldListRequest withAssignedToMe(String assignedToMe) {
        this.assignedToMe = assignedToMe;
        return this;
    }
    
    /**
     * categories
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=categories")
    public MeldListCategories categories;

    public MeldListRequest withCategories(MeldListCategories categories) {
        this.categories = categories;
        return this;
    }
    
    /**
     * comments_gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=comments_gte")
    public String commentsGte;

    public MeldListRequest withCommentsGte(String commentsGte) {
        this.commentsGte = commentsGte;
        return this;
    }
    
    /**
     * comments_lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=comments_lte")
    public String commentsLte;

    public MeldListRequest withCommentsLte(String commentsLte) {
        this.commentsLte = commentsLte;
        return this;
    }
    
    /**
     * completed__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=completed__gte")
    public String completedGte;

    public MeldListRequest withCompletedGte(String completedGte) {
        this.completedGte = completedGte;
        return this;
    }
    
    /**
     * completed__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=completed__interval")
    public String completedInterval;

    public MeldListRequest withCompletedInterval(String completedInterval) {
        this.completedInterval = completedInterval;
        return this;
    }
    
    /**
     * completed__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=completed__lte")
    public String completedLte;

    public MeldListRequest withCompletedLte(String completedLte) {
        this.completedLte = completedLte;
        return this;
    }
    
    /**
     * created__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__gte")
    public String createdGte;

    public MeldListRequest withCreatedGte(String createdGte) {
        this.createdGte = createdGte;
        return this;
    }
    
    /**
     * created__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__interval")
    public String createdInterval;

    public MeldListRequest withCreatedInterval(String createdInterval) {
        this.createdInterval = createdInterval;
        return this;
    }
    
    /**
     * created__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__lte")
    public String createdLte;

    public MeldListRequest withCreatedLte(String createdLte) {
        this.createdLte = createdLte;
        return this;
    }
    
    /**
     * created__offset_lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=created__offset_lte")
    public String createdOffsetLte;

    public MeldListRequest withCreatedOffsetLte(String createdOffsetLte) {
        this.createdOffsetLte = createdOffsetLte;
        return this;
    }
    
    /**
     * due_date_choice
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=due_date_choice")
    public MeldListDueDateChoice dueDateChoice;

    public MeldListRequest withDueDateChoice(MeldListDueDateChoice dueDateChoice) {
        this.dueDateChoice = dueDateChoice;
        return this;
    }
    
    /**
     * due_date_gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=due_date_gte")
    public String dueDateGte;

    public MeldListRequest withDueDateGte(String dueDateGte) {
        this.dueDateGte = dueDateGte;
        return this;
    }
    
    /**
     * due_date_lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=due_date_lte")
    public String dueDateLte;

    public MeldListRequest withDueDateLte(String dueDateLte) {
        this.dueDateLte = dueDateLte;
        return this;
    }
    
    /**
     * ever_been_assigned
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ever_been_assigned")
    public MeldListEverBeenAssigned everBeenAssigned;

    public MeldListRequest withEverBeenAssigned(MeldListEverBeenAssigned everBeenAssigned) {
        this.everBeenAssigned = everBeenAssigned;
        return this;
    }
    
    /**
     * exp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=exp")
    public MeldListExp exp;

    public MeldListRequest withExp(MeldListExp exp) {
        this.exp = exp;
        return this;
    }
    
    /**
     * exp_s
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=exp_s")
    public String expS;

    public MeldListRequest withExpS(String expS) {
        this.expS = expS;
        return this;
    }
    
    /**
     * files_gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=files_gte")
    public String filesGte;

    public MeldListRequest withFilesGte(String filesGte) {
        this.filesGte = filesGte;
        return this;
    }
    
    /**
     * files_lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=files_lte")
    public String filesLte;

    public MeldListRequest withFilesLte(String filesLte) {
        this.filesLte = filesLte;
        return this;
    }
    
    /**
     * has_estimates
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=has_estimates")
    public MeldListHasEstimates hasEstimates;

    public MeldListRequest withHasEstimates(MeldListHasEstimates hasEstimates) {
        this.hasEstimates = hasEstimates;
        return this;
    }
    
    /**
     * invoice_s
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=invoice_s")
    public String invoiceS;

    public MeldListRequest withInvoiceS(String invoiceS) {
        this.invoiceS = invoiceS;
        return this;
    }
    
    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public MeldListRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * maint
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=maint")
    public String maint;

    public MeldListRequest withMaint(String maint) {
        this.maint = maint;
        return this;
    }
    
    /**
     * maint_type
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=maint_type")
    public MeldListMaintType maintType;

    public MeldListRequest withMaintType(MeldListMaintType maintType) {
        this.maintType = maintType;
        return this;
    }
    
    /**
     * marked_complete__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=marked_complete__gte")
    public String markedCompleteGte;

    public MeldListRequest withMarkedCompleteGte(String markedCompleteGte) {
        this.markedCompleteGte = markedCompleteGte;
        return this;
    }
    
    /**
     * marked_complete__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=marked_complete__interval")
    public String markedCompleteInterval;

    public MeldListRequest withMarkedCompleteInterval(String markedCompleteInterval) {
        this.markedCompleteInterval = markedCompleteInterval;
        return this;
    }
    
    /**
     * marked_complete__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=marked_complete__lte")
    public String markedCompleteLte;

    public MeldListRequest withMarkedCompleteLte(String markedCompleteLte) {
        this.markedCompleteLte = markedCompleteLte;
        return this;
    }
    
    /**
     * meldinvoice
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=meldinvoice")
    public MeldListMeldinvoice meldinvoice;

    public MeldListRequest withMeldinvoice(MeldListMeldinvoice meldinvoice) {
        this.meldinvoice = meldinvoice;
        return this;
    }
    
    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public Long offset;

    public MeldListRequest withOffset(Long offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * Ordering
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=order_by")
    public MeldListOrderBy orderBy;

    public MeldListRequest withOrderBy(MeldListOrderBy orderBy) {
        this.orderBy = orderBy;
        return this;
    }
    
    /**
     * owner_approval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=owner_approval")
    public MeldListOwnerApproval ownerApproval;

    public MeldListRequest withOwnerApproval(MeldListOwnerApproval ownerApproval) {
        this.ownerApproval = ownerApproval;
        return this;
    }
    
    /**
     * pg
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pg")
    public String pg;

    public MeldListRequest withPg(String pg) {
        this.pg = pg;
        return this;
    }
    
    /**
     * priority
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=priority")
    public MeldListPriority priority;

    public MeldListRequest withPriority(MeldListPriority priority) {
        this.priority = priority;
        return this;
    }
    
    /**
     * project
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=project")
    public String project;

    public MeldListRequest withProject(String project) {
        this.project = project;
        return this;
    }
    
    /**
     * project_assigned
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=project_assigned")
    public MeldListProjectAssigned projectAssigned;

    public MeldListRequest withProjectAssigned(MeldListProjectAssigned projectAssigned) {
        this.projectAssigned = projectAssigned;
        return this;
    }
    
    /**
     * prop
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=prop")
    public String prop;

    public MeldListRequest withProp(String prop) {
        this.prop = prop;
        return this;
    }
    
    /**
     * rating
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=rating")
    public MeldListRating rating;

    public MeldListRequest withRating(MeldListRating rating) {
        this.rating = rating;
        return this;
    }
    
    /**
     * recurring
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=recurring")
    public MeldListRecurring recurring;

    public MeldListRequest withRecurring(MeldListRecurring recurring) {
        this.recurring = recurring;
        return this;
    }
    
    /**
     * recurring_meld
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=recurring_meld")
    public String recurringMeld;

    public MeldListRequest withRecurringMeld(String recurringMeld) {
        this.recurringMeld = recurringMeld;
        return this;
    }
    
    /**
     * remindees
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=remindees")
    public String remindees;

    public MeldListRequest withRemindees(String remindees) {
        this.remindees = remindees;
        return this;
    }
    
    /**
     * reminder_choice
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reminder_choice")
    public MeldListReminderChoice reminderChoice;

    public MeldListRequest withReminderChoice(MeldListReminderChoice reminderChoice) {
        this.reminderChoice = reminderChoice;
        return this;
    }
    
    /**
     * reminder_gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reminder_gte")
    public String reminderGte;

    public MeldListRequest withReminderGte(String reminderGte) {
        this.reminderGte = reminderGte;
        return this;
    }
    
    /**
     * reminder_lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=reminder_lte")
    public String reminderLte;

    public MeldListRequest withReminderLte(String reminderLte) {
        this.reminderLte = reminderLte;
        return this;
    }
    
    /**
     * scheduled__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scheduled__gte")
    public String scheduledGte;

    public MeldListRequest withScheduledGte(String scheduledGte) {
        this.scheduledGte = scheduledGte;
        return this;
    }
    
    /**
     * scheduled__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scheduled__interval")
    public String scheduledInterval;

    public MeldListRequest withScheduledInterval(String scheduledInterval) {
        this.scheduledInterval = scheduledInterval;
        return this;
    }
    
    /**
     * scheduled__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scheduled__lte")
    public String scheduledLte;

    public MeldListRequest withScheduledLte(String scheduledLte) {
        this.scheduledLte = scheduledLte;
        return this;
    }
    
    /**
     * scheduling
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=scheduling")
    public String scheduling;

    public MeldListRequest withScheduling(String scheduling) {
        this.scheduling = scheduling;
        return this;
    }
    
    /**
     * status
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")
    public MeldListStatus status;

    public MeldListRequest withStatus(MeldListStatus status) {
        this.status = status;
        return this;
    }
    
    /**
     * tags
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=tags")
    public String tags;

    public MeldListRequest withTags(String tags) {
        this.tags = tags;
        return this;
    }
    
    /**
     * tags_ex
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=tags_ex")
    public String tagsEx;

    public MeldListRequest withTagsEx(String tagsEx) {
        this.tagsEx = tagsEx;
        return this;
    }
    
    /**
     * tpr
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=tpr")
    public MeldListTpr tpr;

    public MeldListRequest withTpr(MeldListTpr tpr) {
        this.tpr = tpr;
        return this;
    }
    
    /**
     * unit
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=unit")
    public String unit;

    public MeldListRequest withUnit(String unit) {
        this.unit = unit;
        return this;
    }
    
    /**
     * updated__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=updated__gte")
    public String updatedGte;

    public MeldListRequest withUpdatedGte(String updatedGte) {
        this.updatedGte = updatedGte;
        return this;
    }
    
    /**
     * updated__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=updated__interval")
    public String updatedInterval;

    public MeldListRequest withUpdatedInterval(String updatedInterval) {
        this.updatedInterval = updatedInterval;
        return this;
    }
    
    /**
     * updated__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=updated__lte")
    public String updatedLte;

    public MeldListRequest withUpdatedLte(String updatedLte) {
        this.updatedLte = updatedLte;
        return this;
    }
    
    /**
     * updated__offset_lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=updated__offset_lte")
    public String updatedOffsetLte;

    public MeldListRequest withUpdatedOffsetLte(String updatedOffsetLte) {
        this.updatedOffsetLte = updatedOffsetLte;
        return this;
    }
    
    /**
     * vendor_scheduled__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=vendor_scheduled__gte")
    public String vendorScheduledGte;

    public MeldListRequest withVendorScheduledGte(String vendorScheduledGte) {
        this.vendorScheduledGte = vendorScheduledGte;
        return this;
    }
    
    /**
     * vendor_scheduled__interval
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=vendor_scheduled__interval")
    public String vendorScheduledInterval;

    public MeldListRequest withVendorScheduledInterval(String vendorScheduledInterval) {
        this.vendorScheduledInterval = vendorScheduledInterval;
        return this;
    }
    
    /**
     * vendor_scheduled__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=vendor_scheduled__lte")
    public String vendorScheduledLte;

    public MeldListRequest withVendorScheduledLte(String vendorScheduledLte) {
        this.vendorScheduledLte = vendorScheduledLte;
        return this;
    }
    
    /**
     * wl__gte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=wl__gte")
    public String wlGte;

    public MeldListRequest withWlGte(String wlGte) {
        this.wlGte = wlGte;
        return this;
    }
    
    /**
     * wl__lte
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=wl__lte")
    public String wlLte;

    public MeldListRequest withWlLte(String wlLte) {
        this.wlLte = wlLte;
        return this;
    }
    
    public MeldListRequest(@JsonProperty("X-Pm-Org") Long xPmOrg) {
        this.xPmOrg = xPmOrg;
  }
}
