/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MeldListOrderBy - Ordering
 */
public enum MeldListOrderBy {
    OWNER_APPROVAL_REQUEST_DATE("owner_approval_request_date"),
    MINUS_OWNER_APPROVAL_REQUEST_DATE("-owner_approval_request_date");

    @JsonValue
    public final String value;

    private MeldListOrderBy(String value) {
        this.value = value;
    }
}
