/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;

public class OwnerListRequest {
    /**
     * Number of results to return per page.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Long limit;

    public OwnerListRequest withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    /**
     * The initial index from which to return the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public Long offset;

    public OwnerListRequest withOffset(Long offset) {
        this.offset = offset;
        return this;
    }
    
    /**
     * Which field to use when ordering the results.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ordering")
    public String ordering;

    public OwnerListRequest withOrdering(String ordering) {
        this.ordering = ordering;
        return this;
    }
    
    public OwnerListRequest(){}
}
