/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class OwnerUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.OwnerInput ownerInput;

    public OwnerUpdateRequest withOwnerInput(PropertyMeld.MeldAPI.models.shared.OwnerInput ownerInput) {
        this.ownerInput = ownerInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public OwnerUpdateRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public OwnerUpdateRequest(@JsonProperty("OwnerInput") PropertyMeld.MeldAPI.models.shared.OwnerInput ownerInput, @JsonProperty("id") String id) {
        this.ownerInput = ownerInput;
        this.id = id;
  }
}
