/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class OwnerPartialUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.PatchedOwnerInput patchedOwnerInput;

    public OwnerPartialUpdateRequest withPatchedOwnerInput(PropertyMeld.MeldAPI.models.shared.PatchedOwnerInput patchedOwnerInput) {
        this.patchedOwnerInput = patchedOwnerInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public OwnerPartialUpdateRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public OwnerPartialUpdateRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
