/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PingRetrieveResponse {
    
    public String contentType;

    public PingRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public PingRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PingRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    
    public java.util.Map<String, Object> pingRetrieve200ApplicationJSONObject;

    public PingRetrieveResponse withPingRetrieve200ApplicationJSONObject(java.util.Map<String, Object> pingRetrieve200ApplicationJSONObject) {
        this.pingRetrieve200ApplicationJSONObject = pingRetrieve200ApplicationJSONObject;
        return this;
    }
    
    public PingRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
