/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ProjectRetrieveResponse {
    
    public String contentType;

    public ProjectRetrieveResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PmAPIProjectDetail pmAPIProjectDetail;

    public ProjectRetrieveResponse withPmAPIProjectDetail(PropertyMeld.MeldAPI.models.shared.PmAPIProjectDetail pmAPIProjectDetail) {
        this.pmAPIProjectDetail = pmAPIProjectDetail;
        return this;
    }
    
    
    public Integer statusCode;

    public ProjectRetrieveResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ProjectRetrieveResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ProjectRetrieveResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
