/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ProjectListResponse {
    
    public String contentType;

    public ProjectListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedProjectListViewList paginatedProjectListViewList;

    public ProjectListResponse withPaginatedProjectListViewList(PropertyMeld.MeldAPI.models.shared.PaginatedProjectListViewList paginatedProjectListViewList) {
        this.paginatedProjectListViewList = paginatedProjectListViewList;
        return this;
    }
    
    
    public Integer statusCode;

    public ProjectListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ProjectListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ProjectListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
