/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PropertyRetrieveRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public PropertyRetrieveRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public PropertyRetrieveRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
