/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PropertyGroupListResponse {
    
    public String contentType;

    public PropertyGroupListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedPropertyGroupSerializerListList paginatedPropertyGroupSerializerListList;

    public PropertyGroupListResponse withPaginatedPropertyGroupSerializerListList(PropertyMeld.MeldAPI.models.shared.PaginatedPropertyGroupSerializerListList paginatedPropertyGroupSerializerListList) {
        this.paginatedPropertyGroupSerializerListList = paginatedPropertyGroupSerializerListList;
        return this;
    }
    
    
    public Integer statusCode;

    public PropertyGroupListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PropertyGroupListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PropertyGroupListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
