/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PropertyPartialUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.PatchedPropertyInput patchedPropertyInput;

    public PropertyPartialUpdateRequest withPatchedPropertyInput(PropertyMeld.MeldAPI.models.shared.PatchedPropertyInput patchedPropertyInput) {
        this.patchedPropertyInput = patchedPropertyInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public PropertyPartialUpdateRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public PropertyPartialUpdateRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
