/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ResidentFileListResponse {
    
    public String contentType;

    public ResidentFileListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedTenantMeldFileList paginatedTenantMeldFileList;

    public ResidentFileListResponse withPaginatedTenantMeldFileList(PropertyMeld.MeldAPI.models.shared.PaginatedTenantMeldFileList paginatedTenantMeldFileList) {
        this.paginatedTenantMeldFileList = paginatedTenantMeldFileList;
        return this;
    }
    
    
    public Integer statusCode;

    public ResidentFileListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ResidentFileListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ResidentFileListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
