/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ResidentUpdateJsonRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.ResidentInput residentInput;

    public ResidentUpdateJsonRequest withResidentInput(PropertyMeld.MeldAPI.models.shared.ResidentInput residentInput) {
        this.residentInput = residentInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public ResidentUpdateJsonRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public ResidentUpdateJsonRequest(@JsonProperty("ResidentInput") PropertyMeld.MeldAPI.models.shared.ResidentInput residentInput, @JsonProperty("id") String id) {
        this.residentInput = residentInput;
        this.id = id;
  }
}
