/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ResidentPartialUpdateJsonRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.PatchedResidentInput patchedResidentInput;

    public ResidentPartialUpdateJsonRequest withPatchedResidentInput(PropertyMeld.MeldAPI.models.shared.PatchedResidentInput patchedResidentInput) {
        this.patchedResidentInput = patchedResidentInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public ResidentPartialUpdateJsonRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public ResidentPartialUpdateJsonRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
