/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ResidentPartialUpdateFormRequest {
    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    public PropertyMeld.MeldAPI.models.shared.PatchedResidentInput1 patchedResidentInput1;

    public ResidentPartialUpdateFormRequest withPatchedResidentInput1(PropertyMeld.MeldAPI.models.shared.PatchedResidentInput1 patchedResidentInput1) {
        this.patchedResidentInput1 = patchedResidentInput1;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public ResidentPartialUpdateFormRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public ResidentPartialUpdateFormRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
