/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ResidentPartialUpdateMultipartRequest {
    @SpeakeasyMetadata("request:mediaType=multipart/form-data")
    public PropertyMeld.MeldAPI.models.shared.PatchedResidentInput1 patchedResidentInput1;

    public ResidentPartialUpdateMultipartRequest withPatchedResidentInput1(PropertyMeld.MeldAPI.models.shared.PatchedResidentInput1 patchedResidentInput1) {
        this.patchedResidentInput1 = patchedResidentInput1;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public ResidentPartialUpdateMultipartRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public ResidentPartialUpdateMultipartRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
