/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class SchemaRetrieveRequest {
    /**
     * The management ID (MID), found in the first number of your URL when logged in:  https://app.propertymeld.com/{MID}/m/123
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Pm-Org")
    public Long xPmOrg;

    public SchemaRetrieveRequest withXPmOrg(Long xPmOrg) {
        this.xPmOrg = xPmOrg;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=format")
    public SchemaRetrieveFormat format;

    public SchemaRetrieveRequest withFormat(SchemaRetrieveFormat format) {
        this.format = format;
        return this;
    }
    
    public SchemaRetrieveRequest(@JsonProperty("X-Pm-Org") Long xPmOrg) {
        this.xPmOrg = xPmOrg;
  }
}
