/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UnitPartialUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.PatchedUnitInput patchedUnitInput;

    public UnitPartialUpdateRequest withPatchedUnitInput(PropertyMeld.MeldAPI.models.shared.PatchedUnitInput patchedUnitInput) {
        this.patchedUnitInput = patchedUnitInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public UnitPartialUpdateRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public UnitPartialUpdateRequest(@JsonProperty("id") String id) {
        this.id = id;
  }
}
