/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UnitUpdateRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PropertyMeld.MeldAPI.models.shared.UnitInput unitInput;

    public UnitUpdateRequest withUnitInput(PropertyMeld.MeldAPI.models.shared.UnitInput unitInput) {
        this.unitInput = unitInput;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    public String id;

    public UnitUpdateRequest withId(String id) {
        this.id = id;
        return this;
    }
    
    public UnitUpdateRequest(@JsonProperty("UnitInput") PropertyMeld.MeldAPI.models.shared.UnitInput unitInput, @JsonProperty("id") String id) {
        this.unitInput = unitInput;
        this.id = id;
  }
}
