/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class VendorInviteCreateResponse {
    
    public String contentType;

    public VendorInviteCreateResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public VendorInviteCreateResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public VendorInviteCreateResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.VendorInvite vendorInvite;

    public VendorInviteCreateResponse withVendorInvite(PropertyMeld.MeldAPI.models.shared.VendorInvite vendorInvite) {
        this.vendorInvite = vendorInvite;
        return this;
    }
    
    public VendorInviteCreateResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
