/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class VendorFileListResponse {
    
    public String contentType;

    public VendorFileListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedVendorMeldFileList paginatedVendorMeldFileList;

    public VendorFileListResponse withPaginatedVendorMeldFileList(PropertyMeld.MeldAPI.models.shared.PaginatedVendorMeldFileList paginatedVendorMeldFileList) {
        this.paginatedVendorMeldFileList = paginatedVendorMeldFileList;
        return this;
    }
    
    
    public Integer statusCode;

    public VendorFileListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public VendorFileListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public VendorFileListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
