/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class VendorListResponse {
    
    public String contentType;

    public VendorListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedVendorList paginatedVendorList;

    public VendorListResponse withPaginatedVendorList(PropertyMeld.MeldAPI.models.shared.PaginatedVendorList paginatedVendorList) {
        this.paginatedVendorList = paginatedVendorList;
        return this;
    }
    
    
    public Integer statusCode;

    public VendorListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public VendorListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public VendorListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
