/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class WorkLogListResponse {
    
    public String contentType;

    public WorkLogListResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public PropertyMeld.MeldAPI.models.shared.PaginatedWorkEntrySerializerListList paginatedWorkEntrySerializerListList;

    public WorkLogListResponse withPaginatedWorkEntrySerializerListList(PropertyMeld.MeldAPI.models.shared.PaginatedWorkEntrySerializerListList paginatedWorkEntrySerializerListList) {
        this.paginatedWorkEntrySerializerListList = paginatedWorkEntrySerializerListList;
        return this;
    }
    
    
    public Integer statusCode;

    public WorkLogListResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public WorkLogListResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public WorkLogListResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
