/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BlankEnum {
    UNKNOWN("");

    @JsonValue
    public final String value;

    private BlankEnum(String value) {
        this.value = value;
    }
}
