/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class BuildingSerializerList {
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public BuildingSerializerList withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public BuildingSerializerList withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("number")
    public String number;

    public BuildingSerializerList withNumber(String number) {
        this.number = number;
        return this;
    }
    
    @JsonProperty("prop")
    public Long prop;

    public BuildingSerializerList withProp(Long prop) {
        this.prop = prop;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public BuildingSerializerList withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public BuildingSerializerList(@JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("number") String number, @JsonProperty("prop") Long prop, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.id = id;
        this.number = number;
        this.prop = prop;
        this.updated = updated;
  }
}
