/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Contact {
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_phone")
    public String businessPhone;

    public Contact withBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("business_phone_ext")
    public String businessPhoneExt;

    public Contact withBusinessPhoneExt(String businessPhoneExt) {
        this.businessPhoneExt = businessPhoneExt;
        return this;
    }
    
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cell_phone")
    public String cellPhone;

    public Contact withCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cell_phone_ext")
    public String cellPhoneExt;

    public Contact withCellPhoneExt(String cellPhoneExt) {
        this.cellPhoneExt = cellPhoneExt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fax")
    public String fax;

    public Contact withFax(String fax) {
        this.fax = fax;
        return this;
    }
    
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("home_phone")
    public String homePhone;

    public Contact withHomePhone(String homePhone) {
        this.homePhone = homePhone;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("home_phone_ext")
    public String homePhoneExt;

    public Contact withHomePhoneExt(String homePhoneExt) {
        this.homePhoneExt = homePhoneExt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("primary_email")
    public String primaryEmail;

    public Contact withPrimaryEmail(String primaryEmail) {
        this.primaryEmail = primaryEmail;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("secondary_email")
    public String secondaryEmail;

    public Contact withSecondaryEmail(String secondaryEmail) {
        this.secondaryEmail = secondaryEmail;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tertiary_email")
    public String tertiaryEmail;

    public Contact withTertiaryEmail(String tertiaryEmail) {
        this.tertiaryEmail = tertiaryEmail;
        return this;
    }
    
    public Contact(){}
}
