/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum EstimateStatusEnum {
    ESTIMATE_PENDING_ACCEPTANCE("ESTIMATE_PENDING_ACCEPTANCE"),
    ESTIMATE_IN_PROGRESS("ESTIMATE_IN_PROGRESS"),
    ESTIMATE_SUBMITTED("ESTIMATE_SUBMITTED"),
    ESTIMATE_VENDOR_REJECTED("ESTIMATE_VENDOR_REJECTED"),
    ESTIMATE_OWNER_REJECTED("ESTIMATE_OWNER_REJECTED"),
    ESTIMATE_CLOSED("ESTIMATE_CLOSED"),
    ESTIMATE_PENDING_APPROVAL("ESTIMATE_PENDING_APPROVAL"),
    ESTIMATE_APPROVED("ESTIMATE_APPROVED");

    @JsonValue
    public final String value;

    private EstimateStatusEnum(String value) {
        this.value = value;
    }
}
