/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class EstimateSerializerDetailOutput {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("approval_requested")
    public Boolean approvalRequested;

    public EstimateSerializerDetailOutput withApprovalRequested(Boolean approvalRequested) {
        this.approvalRequested = approvalRequested;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("date_accepted")
    public OffsetDateTime dateAccepted;

    public EstimateSerializerDetailOutput withDateAccepted(OffsetDateTime dateAccepted) {
        this.dateAccepted = dateAccepted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("days_to_complete")
    public Long daysToComplete;

    public EstimateSerializerDetailOutput withDaysToComplete(Long daysToComplete) {
        this.daysToComplete = daysToComplete;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("days_until_start")
    public Long daysUntilStart;

    public EstimateSerializerDetailOutput withDaysUntilStart(Long daysUntilStart) {
        this.daysUntilStart = daysUntilStart;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("deadline")
    public OffsetDateTime deadline;

    public EstimateSerializerDetailOutput withDeadline(OffsetDateTime deadline) {
        this.deadline = deadline;
        return this;
    }
    
    @JsonProperty("estimate_meld")
    public Long estimateMeld;

    public EstimateSerializerDetailOutput withEstimateMeld(Long estimateMeld) {
        this.estimateMeld = estimateMeld;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("estimate_status")
    public EstimateStatusEnum estimateStatus;

    public EstimateSerializerDetailOutput withEstimateStatus(EstimateStatusEnum estimateStatus) {
        this.estimateStatus = estimateStatus;
        return this;
    }
    
    @JsonProperty("get_vendor_email")
    public String getVendorEmail;

    public EstimateSerializerDetailOutput withGetVendorEmail(String getVendorEmail) {
        this.getVendorEmail = getVendorEmail;
        return this;
    }
    
    @JsonProperty("get_vendor_invite_email")
    public String getVendorInviteEmail;

    public EstimateSerializerDetailOutput withGetVendorInviteEmail(String getVendorInviteEmail) {
        this.getVendorInviteEmail = getVendorInviteEmail;
        return this;
    }
    
    @JsonProperty("get_vendor_name")
    public String getVendorName;

    public EstimateSerializerDetailOutput withGetVendorName(String getVendorName) {
        this.getVendorName = getVendorName;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public EstimateSerializerDetailOutput withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("line_items")
    public Long[] lineItems;

    public EstimateSerializerDetailOutput withLineItems(Long[] lineItems) {
        this.lineItems = lineItems;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notes")
    public String notes;

    public EstimateSerializerDetailOutput withNotes(String notes) {
        this.notes = notes;
        return this;
    }
    
    @JsonProperty("original_meld")
    public Long originalMeld;

    public EstimateSerializerDetailOutput withOriginalMeld(Long originalMeld) {
        this.originalMeld = originalMeld;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pm_fee")
    public String pmFee;

    public EstimateSerializerDetailOutput withPmFee(String pmFee) {
        this.pmFee = pmFee;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("servicer")
    public Long servicer;

    public EstimateSerializerDetailOutput withServicer(Long servicer) {
        this.servicer = servicer;
        return this;
    }
    
    @JsonProperty("total")
    public String total;

    public EstimateSerializerDetailOutput withTotal(String total) {
        this.total = total;
        return this;
    }
    
    @JsonProperty("vendor")
    public Long vendor;

    public EstimateSerializerDetailOutput withVendor(Long vendor) {
        this.vendor = vendor;
        return this;
    }
    
    public EstimateSerializerDetailOutput(@JsonProperty("date_accepted") OffsetDateTime dateAccepted, @JsonProperty("estimate_meld") Long estimateMeld, @JsonProperty("get_vendor_email") String getVendorEmail, @JsonProperty("get_vendor_invite_email") String getVendorInviteEmail, @JsonProperty("get_vendor_name") String getVendorName, @JsonProperty("id") Long id, @JsonProperty("line_items") Long[] lineItems, @JsonProperty("original_meld") Long originalMeld, @JsonProperty("total") String total, @JsonProperty("vendor") Long vendor) {
        this.dateAccepted = dateAccepted;
        this.estimateMeld = estimateMeld;
        this.getVendorEmail = getVendorEmail;
        this.getVendorInviteEmail = getVendorInviteEmail;
        this.getVendorName = getVendorName;
        this.id = id;
        this.lineItems = lineItems;
        this.originalMeld = originalMeld;
        this.total = total;
        this.vendor = vendor;
  }
}
