/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class FloorSerializerDetail {
    @JsonProperty("building")
    public Long building;

    public FloorSerializerDetail withBuilding(Long building) {
        this.building = building;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public FloorSerializerDetail withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public FloorSerializerDetail withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public FloorSerializerDetail withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("number")
    public String number;

    public FloorSerializerDetail withNumber(String number) {
        this.number = number;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public FloorSerializerDetail withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public FloorSerializerDetail withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public FloorSerializerDetail(@JsonProperty("building") Long building, @JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("number") String number, @JsonProperty("updated") OffsetDateTime updated) {
        this.building = building;
        this.created = created;
        this.id = id;
        this.number = number;
        this.updated = updated;
  }
}
