/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum HubAccessLevelEnum {
    DIRECT_ONLY("DIRECT_ONLY"),
    ALL_NOTIFICATIONS("ALL_NOTIFICATIONS"),
    INVITED_TO_HUB("INVITED_TO_HUB"),
    HUB_ACCESS("HUB_ACCESS");

    @JsonValue
    public final String value;

    private HubAccessLevelEnum(String value) {
        this.value = value;
    }
}
