/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class ManagementAgentSerializerList {
    @JsonProperty("agent_preferences")
    public Long agentPreferences;

    public ManagementAgentSerializerList withAgentPreferences(Long agentPreferences) {
        this.agentPreferences = agentPreferences;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contact")
    public Long contact;

    public ManagementAgentSerializerList withContact(Long contact) {
        this.contact = contact;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public ManagementAgentSerializerList withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default_invoice_filter")
    public Long defaultInvoiceFilter;

    public ManagementAgentSerializerList withDefaultInvoiceFilter(Long defaultInvoiceFilter) {
        this.defaultInvoiceFilter = defaultInvoiceFilter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default_meld_filter")
    public Long defaultMeldFilter;

    public ManagementAgentSerializerList withDefaultMeldFilter(Long defaultMeldFilter) {
        this.defaultMeldFilter = defaultMeldFilter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("first_name")
    public String firstName;

    public ManagementAgentSerializerList withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public ManagementAgentSerializerList withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public ManagementAgentSerializerList withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_name")
    public String lastName;

    public ManagementAgentSerializerList withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonProperty("management")
    public Long management;

    public ManagementAgentSerializerList withManagement(Long management) {
        this.management = management;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("new_notification_settings")
    public Long newNotificationSettings;

    public ManagementAgentSerializerList withNewNotificationSettings(Long newNotificationSettings) {
        this.newNotificationSettings = newNotificationSettings;
        return this;
    }
    
    @JsonProperty("property_groups")
    public Long[] propertyGroups;

    public ManagementAgentSerializerList withPropertyGroups(Long[] propertyGroups) {
        this.propertyGroups = propertyGroups;
        return this;
    }
    
    @JsonProperty("role")
    public Long role;

    public ManagementAgentSerializerList withRole(Long role) {
        this.role = role;
        return this;
    }
    
    @JsonProperty("title")
    public String title;

    public ManagementAgentSerializerList withTitle(String title) {
        this.title = title;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public ManagementAgentSerializerList withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public ManagementAgentSerializerList(@JsonProperty("agent_preferences") Long agentPreferences, @JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("management") Long management, @JsonProperty("property_groups") Long[] propertyGroups, @JsonProperty("role") Long role, @JsonProperty("title") String title, @JsonProperty("updated") OffsetDateTime updated) {
        this.agentPreferences = agentPreferences;
        this.created = created;
        this.id = id;
        this.management = management;
        this.propertyGroups = propertyGroups;
        this.role = role;
        this.title = title;
        this.updated = updated;
  }
}
