/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldExpendituresListMeld {
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("assigned")
    public OffsetDateTime assigned;

    public MeldExpendituresListMeld withAssigned(OffsetDateTime assigned) {
        this.assigned = assigned;
        return this;
    }
    
    @JsonProperty("assigner")
    public Long assigner;

    public MeldExpendituresListMeld withAssigner(Long assigner) {
        this.assigner = assigner;
        return this;
    }
    
    @JsonProperty("brief_description")
    public String briefDescription;

    public MeldExpendituresListMeld withBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("completion_date")
    public OffsetDateTime completionDate;

    public MeldExpendituresListMeld withCompletionDate(OffsetDateTime completionDate) {
        this.completionDate = completionDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("completion_notes")
    public String completionNotes;

    public MeldExpendituresListMeld withCompletionNotes(String completionNotes) {
        this.completionNotes = completionNotes;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldExpendituresListMeld withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("creator")
    public Long creator;

    public MeldExpendituresListMeld withCreator(Long creator) {
        this.creator = creator;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public MeldExpendituresListMeld withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("due_date")
    public OffsetDateTime dueDate;

    public MeldExpendituresListMeld withDueDate(OffsetDateTime dueDate) {
        this.dueDate = dueDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_pets")
    public Boolean hasPets;

    public MeldExpendituresListMeld withHasPets(Boolean hasPets) {
        this.hasPets = hasPets;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_registered_tenant")
    public Boolean hasRegisteredTenant;

    public MeldExpendituresListMeld withHasRegisteredTenant(Boolean hasRegisteredTenant) {
        this.hasRegisteredTenant = hasRegisteredTenant;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldExpendituresListMeld withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public MeldExpendituresListMeld withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance_notes")
    public String maintenanceNotes;

    public MeldExpendituresListMeld withMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
        return this;
    }
    
    @JsonProperty("management")
    public Long management;

    public MeldExpendituresListMeld withManagement(Long management) {
        this.management = management;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("management_agent_closer")
    public Long managementAgentCloser;

    public MeldExpendituresListMeld withManagementAgentCloser(Long managementAgentCloser) {
        this.managementAgentCloser = managementAgentCloser;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("manager_cancellation_reason")
    public String managerCancellationReason;

    public MeldExpendituresListMeld withManagerCancellationReason(String managerCancellationReason) {
        this.managerCancellationReason = managerCancellationReason;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("manager_cancelled")
    public OffsetDateTime managerCancelled;

    public MeldExpendituresListMeld withManagerCancelled(OffsetDateTime managerCancelled) {
        this.managerCancelled = managerCancelled;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("manager_canceller")
    public Long managerCanceller;

    public MeldExpendituresListMeld withManagerCanceller(Long managerCanceller) {
        this.managerCanceller = managerCanceller;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("marked_complete")
    public OffsetDateTime markedComplete;

    public MeldExpendituresListMeld withMarkedComplete(OffsetDateTime markedComplete) {
        this.markedComplete = markedComplete;
        return this;
    }
    
    @JsonProperty("meld_group")
    public Long meldGroup;

    public MeldExpendituresListMeld withMeldGroup(Long meldGroup) {
        this.meldGroup = meldGroup;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notify_owner")
    public Boolean notifyOwner;

    public MeldExpendituresListMeld withNotifyOwner(Boolean notifyOwner) {
        this.notifyOwner = notifyOwner;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parent")
    public Long parent;

    public MeldExpendituresListMeld withParent(Long parent) {
        this.parent = parent;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pets")
    public String pets;

    public MeldExpendituresListMeld withPets(String pets) {
        this.pets = pets;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("priority")
    public PriorityEnum priority;

    public MeldExpendituresListMeld withPriority(PriorityEnum priority) {
        this.priority = priority;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("project")
    public Long project;

    public MeldExpendituresListMeld withProject(Long project) {
        this.project = project;
        return this;
    }
    
    @JsonProperty("prop")
    public MeldExpendituresListProperty prop;

    public MeldExpendituresListMeld withProp(MeldExpendituresListProperty prop) {
        this.prop = prop;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reason_cannot_complete")
    public String reasonCannotComplete;

    public MeldExpendituresListMeld withReasonCannotComplete(String reasonCannotComplete) {
        this.reasonCannotComplete = reasonCannotComplete;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recurring_meld")
    public Long recurringMeld;

    public MeldExpendituresListMeld withRecurringMeld(Long recurringMeld) {
        this.recurringMeld = recurringMeld;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reference_id")
    public String referenceId;

    public MeldExpendituresListMeld withReferenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reviewing_tenant")
    public Long reviewingTenant;

    public MeldExpendituresListMeld withReviewingTenant(Long reviewingTenant) {
        this.reviewingTenant = reviewingTenant;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("started")
    public OffsetDateTime started;

    public MeldExpendituresListMeld withStarted(OffsetDateTime started) {
        this.started = started;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public Status5c6Enum status;

    public MeldExpendituresListMeld withStatus(Status5c6Enum status) {
        this.status = status;
        return this;
    }
    
    @JsonProperty("tags")
    public Long[] tags;

    public MeldExpendituresListMeld withTags(Long[] tags) {
        this.tags = tags;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_canceller")
    public Long tenantCanceller;

    public MeldExpendituresListMeld withTenantCanceller(Long tenantCanceller) {
        this.tenantCanceller = tenantCanceller;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_presence_required")
    public Boolean tenantPresenceRequired;

    public MeldExpendituresListMeld withTenantPresenceRequired(Boolean tenantPresenceRequired) {
        this.tenantPresenceRequired = tenantPresenceRequired;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_rating")
    public Object tenantRating;

    public MeldExpendituresListMeld withTenantRating(Object tenantRating) {
        this.tenantRating = tenantRating;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_review")
    public String tenantReview;

    public MeldExpendituresListMeld withTenantReview(String tenantReview) {
        this.tenantReview = tenantReview;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("tenant_review_date")
    public OffsetDateTime tenantReviewDate;

    public MeldExpendituresListMeld withTenantReviewDate(OffsetDateTime tenantReviewDate) {
        this.tenantReviewDate = tenantReviewDate;
        return this;
    }
    
    @JsonProperty("unit")
    public MeldExpendituresListUnit unit;

    public MeldExpendituresListMeld withUnit(MeldExpendituresListUnit unit) {
        this.unit = unit;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldExpendituresListMeld withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vendor_closer")
    public Long vendorCloser;

    public MeldExpendituresListMeld withVendorCloser(Long vendorCloser) {
        this.vendorCloser = vendorCloser;
        return this;
    }
    
    @JsonProperty("work_category")
    public WorkCategoryEnum workCategory;

    public MeldExpendituresListMeld withWorkCategory(WorkCategoryEnum workCategory) {
        this.workCategory = workCategory;
        return this;
    }
    
    @JsonProperty("work_location")
    public String workLocation;

    public MeldExpendituresListMeld withWorkLocation(String workLocation) {
        this.workLocation = workLocation;
        return this;
    }
    
    public MeldExpendituresListMeld(@JsonProperty("assigner") Long assigner, @JsonProperty("brief_description") String briefDescription, @JsonProperty("created") OffsetDateTime created, @JsonProperty("creator") Long creator, @JsonProperty("id") Long id, @JsonProperty("management") Long management, @JsonProperty("meld_group") Long meldGroup, @JsonProperty("prop") MeldExpendituresListProperty prop, @JsonProperty("tags") Long[] tags, @JsonProperty("unit") MeldExpendituresListUnit unit, @JsonProperty("updated") OffsetDateTime updated, @JsonProperty("work_category") WorkCategoryEnum workCategory, @JsonProperty("work_location") String workLocation) {
        this.assigner = assigner;
        this.briefDescription = briefDescription;
        this.created = created;
        this.creator = creator;
        this.id = id;
        this.management = management;
        this.meldGroup = meldGroup;
        this.prop = prop;
        this.tags = tags;
        this.unit = unit;
        this.updated = updated;
        this.workCategory = workCategory;
        this.workLocation = workLocation;
  }
}
