/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldSerializerDetailVendorappointment {
    @JsonProperty("assignment_request")
    public Long assignmentRequest;

    public MeldSerializerDetailVendorappointment withAssignmentRequest(Long assignmentRequest) {
        this.assignmentRequest = assignmentRequest;
        return this;
    }
    
    @JsonProperty("availability_segment")
    public VendorAvailabilitySegment availabilitySegment;

    public MeldSerializerDetailVendorappointment withAvailabilitySegment(VendorAvailabilitySegment availabilitySegment) {
        this.availabilitySegment = availabilitySegment;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public MeldSerializerDetailVendorappointment withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldSerializerDetailVendorappointment withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldSerializerDetailVendorappointment withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("meld")
    public Long meld;

    public MeldSerializerDetailVendorappointment withMeld(Long meld) {
        this.meld = meld;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public MeldSerializerDetailVendorappointment withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldSerializerDetailVendorappointment withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public MeldSerializerDetailVendorappointment(@JsonProperty("assignment_request") Long assignmentRequest, @JsonProperty("availability_segment") VendorAvailabilitySegment availabilitySegment, @JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("meld") Long meld, @JsonProperty("updated") OffsetDateTime updated) {
        this.assignmentRequest = assignmentRequest;
        this.availabilitySegment = availabilitySegment;
        this.created = created;
        this.id = id;
        this.meld = meld;
        this.updated = updated;
  }
}
