/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldSerializerListOutput {
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("assigned")
    public OffsetDateTime assigned;

    public MeldSerializerListOutput withAssigned(OffsetDateTime assigned) {
        this.assigned = assigned;
        return this;
    }
    
    @JsonProperty("assigner")
    public Long assigner;

    public MeldSerializerListOutput withAssigner(Long assigner) {
        this.assigner = assigner;
        return this;
    }
    
    @JsonProperty("brief_description")
    public String briefDescription;

    public MeldSerializerListOutput withBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("completion_date")
    public OffsetDateTime completionDate;

    public MeldSerializerListOutput withCompletionDate(OffsetDateTime completionDate) {
        this.completionDate = completionDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("completion_notes")
    public String completionNotes;

    public MeldSerializerListOutput withCompletionNotes(String completionNotes) {
        this.completionNotes = completionNotes;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public MeldSerializerListOutput withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldSerializerListOutput withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("creator")
    public Long creator;

    public MeldSerializerListOutput withCreator(Long creator) {
        this.creator = creator;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public MeldSerializerListOutput withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("due_date")
    public OffsetDateTime dueDate;

    public MeldSerializerListOutput withDueDate(OffsetDateTime dueDate) {
        this.dueDate = dueDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_pets")
    public Boolean hasPets;

    public MeldSerializerListOutput withHasPets(Boolean hasPets) {
        this.hasPets = hasPets;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("has_registered_tenant")
    public Boolean hasRegisteredTenant;

    public MeldSerializerListOutput withHasRegisteredTenant(Boolean hasRegisteredTenant) {
        this.hasRegisteredTenant = hasRegisteredTenant;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldSerializerListOutput withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("in_house_servicers")
    public MeldListViewInHouseMeldServicer[] inHouseServicers;

    public MeldSerializerListOutput withInHouseServicers(MeldListViewInHouseMeldServicer[] inHouseServicers) {
        this.inHouseServicers = inHouseServicers;
        return this;
    }
    
    @JsonProperty("invite_assignments")
    public MeldListViewInviteAssignment[] inviteAssignments;

    public MeldSerializerListOutput withInviteAssignments(MeldListViewInviteAssignment[] inviteAssignments) {
        this.inviteAssignments = inviteAssignments;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public MeldSerializerListOutput withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance_notes")
    public String maintenanceNotes;

    public MeldSerializerListOutput withMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
        return this;
    }
    
    @JsonProperty("management")
    public Long management;

    public MeldSerializerListOutput withManagement(Long management) {
        this.management = management;
        return this;
    }
    
    @JsonProperty("management_agent_closer")
    public MeldSerializerListManagementAgentCloser managementAgentCloser;

    public MeldSerializerListOutput withManagementAgentCloser(MeldSerializerListManagementAgentCloser managementAgentCloser) {
        this.managementAgentCloser = managementAgentCloser;
        return this;
    }
    
    @JsonProperty("managementappointment")
    public MeldSerializerListManagementappointment managementappointment;

    public MeldSerializerListOutput withManagementappointment(MeldSerializerListManagementappointment managementappointment) {
        this.managementappointment = managementappointment;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("manager_cancellation_reason")
    public String managerCancellationReason;

    public MeldSerializerListOutput withManagerCancellationReason(String managerCancellationReason) {
        this.managerCancellationReason = managerCancellationReason;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("manager_cancelled")
    public OffsetDateTime managerCancelled;

    public MeldSerializerListOutput withManagerCancelled(OffsetDateTime managerCancelled) {
        this.managerCancelled = managerCancelled;
        return this;
    }
    
    @JsonProperty("manager_canceller")
    public MeldSerializerListManagerCanceller managerCanceller;

    public MeldSerializerListOutput withManagerCanceller(MeldSerializerListManagerCanceller managerCanceller) {
        this.managerCanceller = managerCanceller;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("marked_complete")
    public OffsetDateTime markedComplete;

    public MeldSerializerListOutput withMarkedComplete(OffsetDateTime markedComplete) {
        this.markedComplete = markedComplete;
        return this;
    }
    
    @JsonProperty("meld_expenditures")
    public MeldSerializerListMeldExpenditures meldExpenditures;

    public MeldSerializerListOutput withMeldExpenditures(MeldSerializerListMeldExpenditures meldExpenditures) {
        this.meldExpenditures = meldExpenditures;
        return this;
    }
    
    @JsonProperty("meld_group")
    public String meldGroup;

    public MeldSerializerListOutput withMeldGroup(String meldGroup) {
        this.meldGroup = meldGroup;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notify_owner")
    public Boolean notifyOwner;

    public MeldSerializerListOutput withNotifyOwner(Boolean notifyOwner) {
        this.notifyOwner = notifyOwner;
        return this;
    }
    
    @JsonProperty("open_work_entry")
    public String openWorkEntry;

    public MeldSerializerListOutput withOpenWorkEntry(String openWorkEntry) {
        this.openWorkEntry = openWorkEntry;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("owner_approval_acknowledged")
    public OffsetDateTime ownerApprovalAcknowledged;

    public MeldSerializerListOutput withOwnerApprovalAcknowledged(OffsetDateTime ownerApprovalAcknowledged) {
        this.ownerApprovalAcknowledged = ownerApprovalAcknowledged;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_approval_comment")
    public String ownerApprovalComment;

    public MeldSerializerListOutput withOwnerApprovalComment(String ownerApprovalComment) {
        this.ownerApprovalComment = ownerApprovalComment;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("owner_approval_completed_date")
    public OffsetDateTime ownerApprovalCompletedDate;

    public MeldSerializerListOutput withOwnerApprovalCompletedDate(OffsetDateTime ownerApprovalCompletedDate) {
        this.ownerApprovalCompletedDate = ownerApprovalCompletedDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_approval_dollar_amount")
    public String ownerApprovalDollarAmount;

    public MeldSerializerListOutput withOwnerApprovalDollarAmount(String ownerApprovalDollarAmount) {
        this.ownerApprovalDollarAmount = ownerApprovalDollarAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("owner_approval_request_date")
    public OffsetDateTime ownerApprovalRequestDate;

    public MeldSerializerListOutput withOwnerApprovalRequestDate(OffsetDateTime ownerApprovalRequestDate) {
        this.ownerApprovalRequestDate = ownerApprovalRequestDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_approval_request_message")
    public String ownerApprovalRequestMessage;

    public MeldSerializerListOutput withOwnerApprovalRequestMessage(String ownerApprovalRequestMessage) {
        this.ownerApprovalRequestMessage = ownerApprovalRequestMessage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_approval_status")
    public OwnerApprovalStatusEnum ownerApprovalStatus;

    public MeldSerializerListOutput withOwnerApprovalStatus(OwnerApprovalStatusEnum ownerApprovalStatus) {
        this.ownerApprovalStatus = ownerApprovalStatus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owner_approved_by")
    public Long ownerApprovedBy;

    public MeldSerializerListOutput withOwnerApprovedBy(Long ownerApprovedBy) {
        this.ownerApprovedBy = ownerApprovedBy;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("owner_notified_assignment")
    public OffsetDateTime ownerNotifiedAssignment;

    public MeldSerializerListOutput withOwnerNotifiedAssignment(OffsetDateTime ownerNotifiedAssignment) {
        this.ownerNotifiedAssignment = ownerNotifiedAssignment;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("parent")
    public Long parent;

    public MeldSerializerListOutput withParent(Long parent) {
        this.parent = parent;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pets")
    public String pets;

    public MeldSerializerListOutput withPets(String pets) {
        this.pets = pets;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("priority")
    public PriorityEnum priority;

    public MeldSerializerListOutput withPriority(PriorityEnum priority) {
        this.priority = priority;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("project")
    public Long project;

    public MeldSerializerListOutput withProject(Long project) {
        this.project = project;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("prop")
    public MeldListViewProperty prop;

    public MeldSerializerListOutput withProp(MeldListViewProperty prop) {
        this.prop = prop;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reason_cannot_complete")
    public String reasonCannotComplete;

    public MeldSerializerListOutput withReasonCannotComplete(String reasonCannotComplete) {
        this.reasonCannotComplete = reasonCannotComplete;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("recurring_meld")
    public Long recurringMeld;

    public MeldSerializerListOutput withRecurringMeld(Long recurringMeld) {
        this.recurringMeld = recurringMeld;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reference_id")
    public String referenceId;

    public MeldSerializerListOutput withReferenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reviewing_tenant")
    public Long reviewingTenant;

    public MeldSerializerListOutput withReviewingTenant(Long reviewingTenant) {
        this.reviewingTenant = reviewingTenant;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("started")
    public OffsetDateTime started;

    public MeldSerializerListOutput withStarted(OffsetDateTime started) {
        this.started = started;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public Status5c6Enum status;

    public MeldSerializerListOutput withStatus(Status5c6Enum status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tags")
    public WriteableTag[] tags;

    public MeldSerializerListOutput withTags(WriteableTag[] tags) {
        this.tags = tags;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_canceller")
    public Long tenantCanceller;

    public MeldSerializerListOutput withTenantCanceller(Long tenantCanceller) {
        this.tenantCanceller = tenantCanceller;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_presence_required")
    public Boolean tenantPresenceRequired;

    public MeldSerializerListOutput withTenantPresenceRequired(Boolean tenantPresenceRequired) {
        this.tenantPresenceRequired = tenantPresenceRequired;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_rating")
    public Object tenantRating;

    public MeldSerializerListOutput withTenantRating(Object tenantRating) {
        this.tenantRating = tenantRating;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenant_review")
    public String tenantReview;

    public MeldSerializerListOutput withTenantReview(String tenantReview) {
        this.tenantReview = tenantReview;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("tenant_review_date")
    public OffsetDateTime tenantReviewDate;

    public MeldSerializerListOutput withTenantReviewDate(OffsetDateTime tenantReviewDate) {
        this.tenantReviewDate = tenantReviewDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenants")
    public Tenant[] tenants;

    public MeldSerializerListOutput withTenants(Tenant[] tenants) {
        this.tenants = tenants;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit")
    public MeldListViewUnit unit;

    public MeldSerializerListOutput withUnit(MeldListViewUnit unit) {
        this.unit = unit;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public MeldSerializerListOutput withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldSerializerListOutput withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vendor_assignment_requests")
    public VendorAssignmentRequest[] vendorAssignmentRequests;

    public MeldSerializerListOutput withVendorAssignmentRequests(VendorAssignmentRequest[] vendorAssignmentRequests) {
        this.vendorAssignmentRequests = vendorAssignmentRequests;
        return this;
    }
    
    @JsonProperty("vendor_closer")
    public MeldSerializerListVendorCloser vendorCloser;

    public MeldSerializerListOutput withVendorCloser(MeldSerializerListVendorCloser vendorCloser) {
        this.vendorCloser = vendorCloser;
        return this;
    }
    
    @JsonProperty("vendorappointment")
    public MeldSerializerListVendorappointment vendorappointment;

    public MeldSerializerListOutput withVendorappointment(MeldSerializerListVendorappointment vendorappointment) {
        this.vendorappointment = vendorappointment;
        return this;
    }
    
    @JsonProperty("work_category")
    public WorkCategoryEnum workCategory;

    public MeldSerializerListOutput withWorkCategory(WorkCategoryEnum workCategory) {
        this.workCategory = workCategory;
        return this;
    }
    
    @JsonProperty("work_location")
    public String workLocation;

    public MeldSerializerListOutput withWorkLocation(String workLocation) {
        this.workLocation = workLocation;
        return this;
    }
    
    public MeldSerializerListOutput(@JsonProperty("assigner") Long assigner, @JsonProperty("brief_description") String briefDescription, @JsonProperty("created") OffsetDateTime created, @JsonProperty("creator") Long creator, @JsonProperty("id") Long id, @JsonProperty("in_house_servicers") MeldListViewInHouseMeldServicer[] inHouseServicers, @JsonProperty("invite_assignments") MeldListViewInviteAssignment[] inviteAssignments, @JsonProperty("management") Long management, @JsonProperty("management_agent_closer") MeldSerializerListManagementAgentCloser managementAgentCloser, @JsonProperty("managementappointment") MeldSerializerListManagementappointment managementappointment, @JsonProperty("manager_canceller") MeldSerializerListManagerCanceller managerCanceller, @JsonProperty("meld_expenditures") MeldSerializerListMeldExpenditures meldExpenditures, @JsonProperty("meld_group") String meldGroup, @JsonProperty("open_work_entry") String openWorkEntry, @JsonProperty("updated") OffsetDateTime updated, @JsonProperty("vendor_closer") MeldSerializerListVendorCloser vendorCloser, @JsonProperty("vendorappointment") MeldSerializerListVendorappointment vendorappointment, @JsonProperty("work_category") WorkCategoryEnum workCategory, @JsonProperty("work_location") String workLocation) {
        this.assigner = assigner;
        this.briefDescription = briefDescription;
        this.created = created;
        this.creator = creator;
        this.id = id;
        this.inHouseServicers = inHouseServicers;
        this.inviteAssignments = inviteAssignments;
        this.management = management;
        this.managementAgentCloser = managementAgentCloser;
        this.managementappointment = managementappointment;
        this.managerCanceller = managerCanceller;
        this.meldExpenditures = meldExpenditures;
        this.meldGroup = meldGroup;
        this.openWorkEntry = openWorkEntry;
        this.updated = updated;
        this.vendorCloser = vendorCloser;
        this.vendorappointment = vendorappointment;
        this.workCategory = workCategory;
        this.workLocation = workLocation;
  }
}
