/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class MeldListViewVendor {
    @JsonProperty("id")
    public Long id;

    public MeldListViewVendor withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public MeldListViewVendor withName(String name) {
        this.name = name;
        return this;
    }
    
    public MeldListViewVendor(@JsonProperty("id") Long id) {
        this.id = id;
  }
}
