/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldSerializerListManagerCanceller {
    @JsonProperty("agent_preferences")
    public Long agentPreferences;

    public MeldSerializerListManagerCanceller withAgentPreferences(Long agentPreferences) {
        this.agentPreferences = agentPreferences;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contact")
    public Long contact;

    public MeldSerializerListManagerCanceller withContact(Long contact) {
        this.contact = contact;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public MeldSerializerListManagerCanceller withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldSerializerListManagerCanceller withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default_invoice_filter")
    public Long defaultInvoiceFilter;

    public MeldSerializerListManagerCanceller withDefaultInvoiceFilter(Long defaultInvoiceFilter) {
        this.defaultInvoiceFilter = defaultInvoiceFilter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default_meld_filter")
    public Long defaultMeldFilter;

    public MeldSerializerListManagerCanceller withDefaultMeldFilter(Long defaultMeldFilter) {
        this.defaultMeldFilter = defaultMeldFilter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("first_name")
    public String firstName;

    public MeldSerializerListManagerCanceller withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldSerializerListManagerCanceller withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public MeldSerializerListManagerCanceller withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_name")
    public String lastName;

    public MeldSerializerListManagerCanceller withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonProperty("management")
    public Long management;

    public MeldSerializerListManagerCanceller withManagement(Long management) {
        this.management = management;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("new_notification_settings")
    public Long newNotificationSettings;

    public MeldSerializerListManagerCanceller withNewNotificationSettings(Long newNotificationSettings) {
        this.newNotificationSettings = newNotificationSettings;
        return this;
    }
    
    @JsonProperty("property_groups")
    public Long[] propertyGroups;

    public MeldSerializerListManagerCanceller withPropertyGroups(Long[] propertyGroups) {
        this.propertyGroups = propertyGroups;
        return this;
    }
    
    @JsonProperty("role")
    public Long role;

    public MeldSerializerListManagerCanceller withRole(Long role) {
        this.role = role;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("show_tour")
    public Boolean showTour;

    public MeldSerializerListManagerCanceller withShowTour(Boolean showTour) {
        this.showTour = showTour;
        return this;
    }
    
    @JsonProperty("title")
    public String title;

    public MeldSerializerListManagerCanceller withTitle(String title) {
        this.title = title;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public MeldSerializerListManagerCanceller withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldSerializerListManagerCanceller withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public Long user;

    public MeldSerializerListManagerCanceller withUser(Long user) {
        this.user = user;
        return this;
    }
    
    public MeldSerializerListManagerCanceller(@JsonProperty("agent_preferences") Long agentPreferences, @JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("management") Long management, @JsonProperty("property_groups") Long[] propertyGroups, @JsonProperty("role") Long role, @JsonProperty("title") String title, @JsonProperty("updated") OffsetDateTime updated) {
        this.agentPreferences = agentPreferences;
        this.created = created;
        this.id = id;
        this.management = management;
        this.propertyGroups = propertyGroups;
        this.role = role;
        this.title = title;
        this.updated = updated;
  }
}
