/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldExpendituresListUnit {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("apartment")
    public String apartment;

    public MeldExpendituresListUnit withApartment(String apartment) {
        this.apartment = apartment;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("approval_currency_limit")
    public String approvalCurrencyLimit;

    public MeldExpendituresListUnit withApprovalCurrencyLimit(String approvalCurrencyLimit) {
        this.approvalCurrencyLimit = approvalCurrencyLimit;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("building")
    public Long building;

    public MeldExpendituresListUnit withBuilding(Long building) {
        this.building = building;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldExpendituresListUnit withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("department")
    public String department;

    public MeldExpendituresListUnit withDepartment(String department) {
        this.department = department;
        return this;
    }
    
    @JsonProperty("display_address")
    public MeldExpendituresListUnitDisplayAddress displayAddress;

    public MeldExpendituresListUnit withDisplayAddress(MeldExpendituresListUnitDisplayAddress displayAddress) {
        this.displayAddress = displayAddress;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("floor")
    public Long floor;

    public MeldExpendituresListUnit withFloor(Long floor) {
        this.floor = floor;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldExpendituresListUnit withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public MeldExpendituresListUnit withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance_notes")
    public String maintenanceNotes;

    public MeldExpendituresListUnit withMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
        return this;
    }
    
    @JsonProperty("prop")
    public MeldExpendituresListProperty prop;

    public MeldExpendituresListUnit withProp(MeldExpendituresListProperty prop) {
        this.prop = prop;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("room")
    public String room;

    public MeldExpendituresListUnit withRoom(String room) {
        this.room = room;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("suite")
    public String suite;

    public MeldExpendituresListUnit withSuite(String suite) {
        this.suite = suite;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit")
    public String unit;

    public MeldExpendituresListUnit withUnit(String unit) {
        this.unit = unit;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit_address")
    public Long unitAddress;

    public MeldExpendituresListUnit withUnitAddress(Long unitAddress) {
        this.unitAddress = unitAddress;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldExpendituresListUnit withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public MeldExpendituresListUnit(@JsonProperty("created") OffsetDateTime created, @JsonProperty("display_address") MeldExpendituresListUnitDisplayAddress displayAddress, @JsonProperty("id") Long id, @JsonProperty("prop") MeldExpendituresListProperty prop, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.displayAddress = displayAddress;
        this.id = id;
        this.prop = prop;
        this.updated = updated;
  }
}
