/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class MeldListViewInHouseMeldServicer {
    @JsonProperty("agent")
    public MeldListViewManagementAgent agent;

    public MeldListViewInHouseMeldServicer withAgent(MeldListViewManagementAgent agent) {
        this.agent = agent;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldListViewInHouseMeldServicer withId(Long id) {
        this.id = id;
        return this;
    }
    
    public MeldListViewInHouseMeldServicer(@JsonProperty("agent") MeldListViewManagementAgent agent, @JsonProperty("id") Long id) {
        this.agent = agent;
        this.id = id;
  }
}
