/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldListViewInviteAssignment {
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("accepted")
    public OffsetDateTime accepted;

    public MeldListViewInviteAssignment withAccepted(OffsetDateTime accepted) {
        this.accepted = accepted;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("canceled")
    public OffsetDateTime canceled;

    public MeldListViewInviteAssignment withCanceled(OffsetDateTime canceled) {
        this.canceled = canceled;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public MeldListViewInviteAssignment withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldListViewInviteAssignment withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldListViewInviteAssignment withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("invite_group")
    public InviteGroup inviteGroup;

    public MeldListViewInviteAssignment withInviteGroup(InviteGroup inviteGroup) {
        this.inviteGroup = inviteGroup;
        return this;
    }
    
    @JsonProperty("meld")
    public Long meld;

    public MeldListViewInviteAssignment withMeld(Long meld) {
        this.meld = meld;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public MeldListViewInviteAssignment withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldListViewInviteAssignment withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public MeldListViewInviteAssignment(@JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("invite_group") InviteGroup inviteGroup, @JsonProperty("meld") Long meld, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.id = id;
        this.inviteGroup = inviteGroup;
        this.meld = meld;
        this.updated = updated;
  }
}
