/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldInvoiceListMeld {
    @JsonProperty("brief_description")
    public String briefDescription;

    public MeldInvoiceListMeld withBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldInvoiceListMeld withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldInvoiceListMeld withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("prop")
    public MeldInvoiceListProperty prop;

    public MeldInvoiceListMeld withProp(MeldInvoiceListProperty prop) {
        this.prop = prop;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reference_id")
    public String referenceId;

    public MeldInvoiceListMeld withReferenceId(String referenceId) {
        this.referenceId = referenceId;
        return this;
    }
    
    @JsonProperty("unit")
    public MeldInvoiceListViewUnit unit;

    public MeldInvoiceListMeld withUnit(MeldInvoiceListViewUnit unit) {
        this.unit = unit;
        return this;
    }
    
    public MeldInvoiceListMeld(@JsonProperty("brief_description") String briefDescription, @JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("prop") MeldInvoiceListProperty prop, @JsonProperty("unit") MeldInvoiceListViewUnit unit) {
        this.briefDescription = briefDescription;
        this.created = created;
        this.id = id;
        this.prop = prop;
        this.unit = unit;
  }
}
