/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class MeldExpendituresListUnitDisplayAddress {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("city")
    public String city;

    public MeldExpendituresListUnitDisplayAddress withCity(String city) {
        this.city = city;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    public String country;

    public MeldExpendituresListUnitDisplayAddress withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("county_province")
    public String countyProvince;

    public MeldExpendituresListUnitDisplayAddress withCountyProvince(String countyProvince) {
        this.countyProvince = countyProvince;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public MeldExpendituresListUnitDisplayAddress withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public MeldExpendituresListUnitDisplayAddress withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public MeldExpendituresListUnitDisplayAddress withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public MeldExpendituresListUnitDisplayAddress withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_1")
    public String line1;

    public MeldExpendituresListUnitDisplayAddress withLine1(String line1) {
        this.line1 = line1;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_2")
    public String line2;

    public MeldExpendituresListUnitDisplayAddress withLine2(String line2) {
        this.line2 = line2;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_3")
    public String line3;

    public MeldExpendituresListUnitDisplayAddress withLine3(String line3) {
        this.line3 = line3;
        return this;
    }
    
    @JsonProperty("postcode")
    public String postcode;

    public MeldExpendituresListUnitDisplayAddress withPostcode(String postcode) {
        this.postcode = postcode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("property_name")
    public String propertyName;

    public MeldExpendituresListUnitDisplayAddress withPropertyName(String propertyName) {
        this.propertyName = propertyName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public MeldExpendituresListUnitDisplayAddress withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public MeldExpendituresListUnitDisplayAddress withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public MeldExpendituresListUnitDisplayAddress(@JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("postcode") String postcode, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.id = id;
        this.postcode = postcode;
        this.updated = updated;
  }
}
