/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class NotificationSettings {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("incoming_meld_frequency")
    public IncomingMeldFrequencyEnum incomingMeldFrequency;

    public NotificationSettings withIncomingMeldFrequency(IncomingMeldFrequencyEnum incomingMeldFrequency) {
        this.incomingMeldFrequency = incomingMeldFrequency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sms_notifications")
    public Boolean smsNotifications;

    public NotificationSettings withSmsNotifications(Boolean smsNotifications) {
        this.smsNotifications = smsNotifications;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("successful_meld_frequency")
    public SuccessfulMeldFrequencyEnum successfulMeldFrequency;

    public NotificationSettings withSuccessfulMeldFrequency(SuccessfulMeldFrequencyEnum successfulMeldFrequency) {
        this.successfulMeldFrequency = successfulMeldFrequency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timezone")
    public TimezoneEnum timezone;

    public NotificationSettings withTimezone(TimezoneEnum timezone) {
        this.timezone = timezone;
        return this;
    }
    
    @JsonProperty("timezone_has_been_set")
    public Boolean timezoneHasBeenSet;

    public NotificationSettings withTimezoneHasBeenSet(Boolean timezoneHasBeenSet) {
        this.timezoneHasBeenSet = timezoneHasBeenSet;
        return this;
    }
    
    public NotificationSettings(@JsonProperty("timezone_has_been_set") Boolean timezoneHasBeenSet) {
        this.timezoneHasBeenSet = timezoneHasBeenSet;
  }
}
