/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class NotificationSettingsInput {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("incoming_meld_frequency")
    public IncomingMeldFrequencyEnum incomingMeldFrequency;

    public NotificationSettingsInput withIncomingMeldFrequency(IncomingMeldFrequencyEnum incomingMeldFrequency) {
        this.incomingMeldFrequency = incomingMeldFrequency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sms_notifications")
    public Boolean smsNotifications;

    public NotificationSettingsInput withSmsNotifications(Boolean smsNotifications) {
        this.smsNotifications = smsNotifications;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("successful_meld_frequency")
    public SuccessfulMeldFrequencyEnum successfulMeldFrequency;

    public NotificationSettingsInput withSuccessfulMeldFrequency(SuccessfulMeldFrequencyEnum successfulMeldFrequency) {
        this.successfulMeldFrequency = successfulMeldFrequency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timezone")
    public TimezoneEnum timezone;

    public NotificationSettingsInput withTimezone(TimezoneEnum timezone) {
        this.timezone = timezone;
        return this;
    }
    
    public NotificationSettingsInput(){}
}
