/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum NullEnum {
    LESS_THAN_NIL_GREATER_THAN("<nil>");

    @JsonValue
    public final String value;

    private NullEnum(String value) {
        this.value = value;
    }
}
