/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class Owner {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    public Address address;

    public Owner withAddress(Address address) {
        this.address = address;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contact")
    public Contact contact;

    public Owner withContact(Contact contact) {
        this.contact = contact;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public Owner withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("email")
    public String email;

    public Owner withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("first_name")
    public String firstName;

    public Owner withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hub_access_level")
    public HubAccessLevelEnum hubAccessLevel;

    public Owner withHubAccessLevel(HubAccessLevelEnum hubAccessLevel) {
        this.hubAccessLevel = hubAccessLevel;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public Owner withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("invited_to_hub")
    public Boolean invitedToHub;

    public Owner withInvitedToHub(Boolean invitedToHub) {
        this.invitedToHub = invitedToHub;
        return this;
    }
    
    @JsonProperty("is_active")
    public Boolean isActive;

    public Owner withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonProperty("last_name")
    public String lastName;

    public Owner withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("properties")
    public Long[] properties;

    public Owner withProperties(Long[] properties) {
        this.properties = properties;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public Owner withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public Owner(@JsonProperty("created") OffsetDateTime created, @JsonProperty("email") String email, @JsonProperty("first_name") String firstName, @JsonProperty("id") Long id, @JsonProperty("is_active") Boolean isActive, @JsonProperty("last_name") String lastName, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.email = email;
        this.firstName = firstName;
        this.id = id;
        this.isActive = isActive;
        this.lastName = lastName;
        this.updated = updated;
  }
}
