/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum OwnerApprovalStatusEnum {
    OWNER_APPROVAL_NOT_REQUESTED("OWNER_APPROVAL_NOT_REQUESTED"),
    OWNER_APPROVAL_REQUESTED("OWNER_APPROVAL_REQUESTED"),
    OWNER_APPROVAL_APPROVED("OWNER_APPROVAL_APPROVED"),
    OWNER_APPROVAL_NOT_APPROVED("OWNER_APPROVAL_NOT_APPROVED"),
    OWNER_APPROVAL_REQUESTED_ESTIMATES("OWNER_APPROVAL_REQUESTED_ESTIMATES");

    @JsonValue
    public final String value;

    private OwnerApprovalStatusEnum(String value) {
        this.value = value;
    }
}
