/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PatchedUnitInput {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("approval_currency_limit")
    @SpeakeasyMetadata("form:name=approval_currency_limit multipartForm:name=approval_currency_limit")
    public String approvalCurrencyLimit;

    public PatchedUnitInput withApprovalCurrencyLimit(String approvalCurrencyLimit) {
        this.approvalCurrencyLimit = approvalCurrencyLimit;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("current_residents")
    @SpeakeasyMetadata("form:name=current_residents multipartForm:name=current_residents")
    public Long[] currentResidents;

    public PatchedUnitInput withCurrentResidents(Long[] currentResidents) {
        this.currentResidents = currentResidents;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance_notes")
    @SpeakeasyMetadata("form:name=maintenance_notes multipartForm:name=maintenance_notes")
    public String maintenanceNotes;

    public PatchedUnitInput withMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("property_id")
    @SpeakeasyMetadata("form:name=property_id multipartForm:name=property_id")
    public Long propertyId;

    public PatchedUnitInput withPropertyId(Long propertyId) {
        this.propertyId = propertyId;
        return this;
    }
    
    /**
     * This field indicates the particular dwelling within a larger building or complex. For example, in the address 123 Main St, Unit 302, the unit is 302
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit")
    @SpeakeasyMetadata("form:name=unit multipartForm:name=unit")
    public String unit;

    public PatchedUnitInput withUnit(String unit) {
        this.unit = unit;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit_address")
    @SpeakeasyMetadata("form:name=unit_address,json multipartForm:name=unit_address,json")
    public Address unitAddress;

    public PatchedUnitInput withUnitAddress(Address unitAddress) {
        this.unitAddress = unitAddress;
        return this;
    }
    
    public PatchedUnitInput(){}
}
