/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PatchedPropertyInput {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("city")
    @SpeakeasyMetadata("form:name=city multipartForm:name=city")
    public String city;

    public PatchedPropertyInput withCity(String city) {
        this.city = city;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    @SpeakeasyMetadata("form:name=country multipartForm:name=country")
    public String country;

    public PatchedPropertyInput withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("county_province")
    @SpeakeasyMetadata("form:name=county_province multipartForm:name=county_province")
    public String countyProvince;

    public PatchedPropertyInput withCountyProvince(String countyProvince) {
        this.countyProvince = countyProvince;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_1")
    @SpeakeasyMetadata("form:name=line_1 multipartForm:name=line_1")
    public String line1;

    public PatchedPropertyInput withLine1(String line1) {
        this.line1 = line1;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_2")
    @SpeakeasyMetadata("form:name=line_2 multipartForm:name=line_2")
    public String line2;

    public PatchedPropertyInput withLine2(String line2) {
        this.line2 = line2;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_3")
    @SpeakeasyMetadata("form:name=line_3 multipartForm:name=line_3")
    public String line3;

    public PatchedPropertyInput withLine3(String line3) {
        this.line3 = line3;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance_notes")
    @SpeakeasyMetadata("form:name=maintenance_notes multipartForm:name=maintenance_notes")
    public String maintenanceNotes;

    public PatchedPropertyInput withMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("other_address_details")
    @SpeakeasyMetadata("form:name=other_address_details multipartForm:name=other_address_details")
    public String otherAddressDetails;

    public PatchedPropertyInput withOtherAddressDetails(String otherAddressDetails) {
        this.otherAddressDetails = otherAddressDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("owners")
    @SpeakeasyMetadata("form:name=owners multipartForm:name=owners")
    public Long[] owners;

    public PatchedPropertyInput withOwners(Long[] owners) {
        this.owners = owners;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postcode")
    @SpeakeasyMetadata("form:name=postcode multipartForm:name=postcode")
    public String postcode;

    public PatchedPropertyInput withPostcode(String postcode) {
        this.postcode = postcode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("property_groups")
    @SpeakeasyMetadata("form:name=property_groups multipartForm:name=property_groups")
    public Long[] propertyGroups;

    public PatchedPropertyInput withPropertyGroups(Long[] propertyGroups) {
        this.propertyGroups = propertyGroups;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("property_name")
    @SpeakeasyMetadata("form:name=property_name multipartForm:name=property_name")
    public String propertyName;

    public PatchedPropertyInput withPropertyName(String propertyName) {
        this.propertyName = propertyName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("units")
    @SpeakeasyMetadata("form:name=units multipartForm:name=units")
    public Long[] units;

    public PatchedPropertyInput withUnits(Long[] units) {
        this.units = units;
        return this;
    }
    
    public PatchedPropertyInput(){}
}
