/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PatchedResidentAddress {
    @JsonProperty("city")
    public String city;

    public PatchedResidentAddress withCity(String city) {
        this.city = city;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("country")
    public String country;

    public PatchedResidentAddress withCountry(String country) {
        this.country = country;
        return this;
    }
    
    @JsonProperty("county_province")
    public String countyProvince;

    public PatchedResidentAddress withCountyProvince(String countyProvince) {
        this.countyProvince = countyProvince;
        return this;
    }
    
    @JsonProperty("line_1")
    public String line1;

    public PatchedResidentAddress withLine1(String line1) {
        this.line1 = line1;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_2")
    public String line2;

    public PatchedResidentAddress withLine2(String line2) {
        this.line2 = line2;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_3")
    public String line3;

    public PatchedResidentAddress withLine3(String line3) {
        this.line3 = line3;
        return this;
    }
    
    @JsonProperty("postcode")
    public String postcode;

    public PatchedResidentAddress withPostcode(String postcode) {
        this.postcode = postcode;
        return this;
    }
    
    public PatchedResidentAddress(@JsonProperty("city") String city, @JsonProperty("county_province") String countyProvince, @JsonProperty("line_1") String line1, @JsonProperty("postcode") String postcode) {
        this.city = city;
        this.countyProvince = countyProvince;
        this.line1 = line1;
        this.postcode = postcode;
  }
}
