/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PatchedOwnerInput {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("address")
    @SpeakeasyMetadata("form:name=address,json multipartForm:name=address,json")
    public Address address;

    public PatchedOwnerInput withAddress(Address address) {
        this.address = address;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contact")
    @SpeakeasyMetadata("form:name=contact,json multipartForm:name=contact,json")
    public Contact contact;

    public PatchedOwnerInput withContact(Contact contact) {
        this.contact = contact;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    @SpeakeasyMetadata("form:name=email multipartForm:name=email")
    public String email;

    public PatchedOwnerInput withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("first_name")
    @SpeakeasyMetadata("form:name=first_name multipartForm:name=first_name")
    public String firstName;

    public PatchedOwnerInput withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hub_access_level")
    @SpeakeasyMetadata("form:name=hub_access_level multipartForm:name=hub_access_level")
    public HubAccessLevelEnum hubAccessLevel;

    public PatchedOwnerInput withHubAccessLevel(HubAccessLevelEnum hubAccessLevel) {
        this.hubAccessLevel = hubAccessLevel;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("invited_to_hub")
    @SpeakeasyMetadata("form:name=invited_to_hub multipartForm:name=invited_to_hub")
    public Boolean invitedToHub;

    public PatchedOwnerInput withInvitedToHub(Boolean invitedToHub) {
        this.invitedToHub = invitedToHub;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_name")
    @SpeakeasyMetadata("form:name=last_name multipartForm:name=last_name")
    public String lastName;

    public PatchedOwnerInput withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("properties")
    @SpeakeasyMetadata("form:name=properties multipartForm:name=properties")
    public Long[] properties;

    public PatchedOwnerInput withProperties(Long[] properties) {
        this.properties = properties;
        return this;
    }
    
    public PatchedOwnerInput(){}
}
