/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class ProjectListViewSerializerUnit {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("apartment")
    public String apartment;

    public ProjectListViewSerializerUnit withApartment(String apartment) {
        this.apartment = apartment;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public ProjectListViewSerializerUnit withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("department")
    public String department;

    public ProjectListViewSerializerUnit withDepartment(String department) {
        this.department = department;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public ProjectListViewSerializerUnit withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public ProjectListViewSerializerUnit withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("maintenance_notes")
    public String maintenanceNotes;

    public ProjectListViewSerializerUnit withMaintenanceNotes(String maintenanceNotes) {
        this.maintenanceNotes = maintenanceNotes;
        return this;
    }
    
    @JsonProperty("prop")
    public ProjectListViewSerializerProperty prop;

    public ProjectListViewSerializerUnit withProp(ProjectListViewSerializerProperty prop) {
        this.prop = prop;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("room")
    public String room;

    public ProjectListViewSerializerUnit withRoom(String room) {
        this.room = room;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("suite")
    public String suite;

    public ProjectListViewSerializerUnit withSuite(String suite) {
        this.suite = suite;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("unit")
    public String unit;

    public ProjectListViewSerializerUnit withUnit(String unit) {
        this.unit = unit;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public ProjectListViewSerializerUnit withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public ProjectListViewSerializerUnit(@JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("prop") ProjectListViewSerializerProperty prop, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.id = id;
        this.prop = prop;
        this.updated = updated;
  }
}
