/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ProjectTypeEnum {
    OTHER("OTHER"),
    RENOVATION("RENOVATION"),
    TURN("TURN"),
    MITIGATION("MITIGATION");

    @JsonValue
    public final String value;

    private ProjectTypeEnum(String value) {
        this.value = value;
    }
}
