/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class ProjectListViewSerializerManagementAgent {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("contact")
    public Long contact;

    public ProjectListViewSerializerManagementAgent withContact(Long contact) {
        this.contact = contact;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public ProjectListViewSerializerManagementAgent withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default_invoice_filter")
    public Long defaultInvoiceFilter;

    public ProjectListViewSerializerManagementAgent withDefaultInvoiceFilter(Long defaultInvoiceFilter) {
        this.defaultInvoiceFilter = defaultInvoiceFilter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("default_meld_filter")
    public Long defaultMeldFilter;

    public ProjectListViewSerializerManagementAgent withDefaultMeldFilter(Long defaultMeldFilter) {
        this.defaultMeldFilter = defaultMeldFilter;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("first_name")
    public String firstName;

    public ProjectListViewSerializerManagementAgent withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public ProjectListViewSerializerManagementAgent withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("is_active")
    public Boolean isActive;

    public ProjectListViewSerializerManagementAgent withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_name")
    public String lastName;

    public ProjectListViewSerializerManagementAgent withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonProperty("role")
    public Long role;

    public ProjectListViewSerializerManagementAgent withRole(Long role) {
        this.role = role;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public ProjectListViewSerializerManagementAgent withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public ProjectListViewSerializerManagementAgent(@JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("role") Long role, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.id = id;
        this.role = role;
        this.updated = updated;
  }
}
