/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ResidentInput1 {
    @SpeakeasyMetadata("form:name=address,json multipartForm:name=address,json")
    public Object address;

    public ResidentInput1 withAddress(Object address) {
        this.address = address;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=contact,json multipartForm:name=contact,json")
    public Contact contact;

    public ResidentInput1 withContact(Contact contact) {
        this.contact = contact;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=first_name multipartForm:name=first_name")
    public String firstName;

    public ResidentInput1 withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    /**
     * Send an invite to the resident to access PropertyMeld
     */
    @SpeakeasyMetadata("form:name=invite multipartForm:name=invite")
    public Boolean invite;

    public ResidentInput1 withInvite(Boolean invite) {
        this.invite = invite;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=last_name multipartForm:name=last_name")
    public String lastName;

    public ResidentInput1 withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=middle_name multipartForm:name=middle_name")
    public String middleName;

    public ResidentInput1 withMiddleName(String middleName) {
        this.middleName = middleName;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=notes multipartForm:name=notes")
    public String notes;

    public ResidentInput1 withNotes(String notes) {
        this.notes = notes;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=notification_settings,json multipartForm:name=notification_settings,json")
    public NotificationSettingsInput notificationSettings;

    public ResidentInput1 withNotificationSettings(NotificationSettingsInput notificationSettings) {
        this.notificationSettings = notificationSettings;
        return this;
    }
    
    @SpeakeasyMetadata("form:name=units multipartForm:name=units")
    public Long[] units;

    public ResidentInput1 withUnits(Long[] units) {
        this.units = units;
        return this;
    }
    
    public ResidentInput1(@JsonProperty("first_name") String firstName, @JsonProperty("last_name") String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
  }
}
