/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum StatusD0bEnum {
    DRAFT("DRAFT"),
    IN_REVIEW("IN_REVIEW"),
    HOLD("HOLD"),
    APPROVED("APPROVED"),
    BILLED("BILLED");

    @JsonValue
    public final String value;

    private StatusD0bEnum(String value) {
        this.value = value;
    }
}
