/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Status09fEnum {
    DRAFT("DRAFT"),
    SUBMITTED("SUBMITTED"),
    IN_REVIEW("IN_REVIEW"),
    HOLD("HOLD"),
    DECLINED("DECLINED"),
    APPROVED("APPROVED"),
    PAID("PAID");

    @JsonValue
    public final String value;

    private Status09fEnum(String value) {
        this.value = value;
    }
}
