/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class TenantMeldFile {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cloned")
    public Boolean cloned;

    public TenantMeldFile withCloned(Boolean cloned) {
        this.cloned = cloned;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public TenantMeldFile withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("filename")
    public String filename;

    public TenantMeldFile withFilename(String filename) {
        this.filename = filename;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hidden_from_owner")
    public Boolean hiddenFromOwner;

    public TenantMeldFile withHiddenFromOwner(Boolean hiddenFromOwner) {
        this.hiddenFromOwner = hiddenFromOwner;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hidden_from_tenant")
    public Boolean hiddenFromTenant;

    public TenantMeldFile withHiddenFromTenant(Boolean hiddenFromTenant) {
        this.hiddenFromTenant = hiddenFromTenant;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hidden_from_vendor")
    public Boolean hiddenFromVendor;

    public TenantMeldFile withHiddenFromVendor(Boolean hiddenFromVendor) {
        this.hiddenFromVendor = hiddenFromVendor;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public TenantMeldFile withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("meld")
    public Long meld;

    public TenantMeldFile withMeld(Long meld) {
        this.meld = meld;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public TenantMeldFile withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("uploader")
    public Long uploader;

    public TenantMeldFile withUploader(Long uploader) {
        this.uploader = uploader;
        return this;
    }
    
    @JsonProperty("url")
    public String url;

    public TenantMeldFile withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public TenantMeldFile(@JsonProperty("created") OffsetDateTime created, @JsonProperty("filename") String filename, @JsonProperty("id") Long id, @JsonProperty("meld") Long meld, @JsonProperty("updated") OffsetDateTime updated, @JsonProperty("url") String url) {
        this.created = created;
        this.filename = filename;
        this.id = id;
        this.meld = meld;
        this.updated = updated;
        this.url = url;
  }
}
