/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class Vendor {
    @JsonProperty("address")
    public Address address;

    public Vendor withAddress(Address address) {
        this.address = address;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public Vendor withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public Vendor withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonProperty("excluded_property_groups")
    public Long[] excludedPropertyGroups;

    public Vendor withExcludedPropertyGroups(Long[] excludedPropertyGroups) {
        this.excludedPropertyGroups = excludedPropertyGroups;
        return this;
    }
    
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("fax")
    public String fax;

    public Vendor withFax(String fax) {
        this.fax = fax;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public Vendor withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("is_active")
    public Boolean isActive;

    public Vendor withIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public Vendor withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * Home phone number. Must be in E.164 format, e.g. '+14155552671'.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    public String phone;

    public Vendor withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public Vendor withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public Vendor(@JsonProperty("address") Address address, @JsonProperty("created") OffsetDateTime created, @JsonProperty("excluded_property_groups") Long[] excludedPropertyGroups, @JsonProperty("id") Long id, @JsonProperty("is_active") Boolean isActive, @JsonProperty("updated") OffsetDateTime updated) {
        this.address = address;
        this.created = created;
        this.excludedPropertyGroups = excludedPropertyGroups;
        this.id = id;
        this.isActive = isActive;
        this.updated = updated;
  }
}
