/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class VendorInvite {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_name")
    @SpeakeasyMetadata("form:name=company_name multipartForm:name=company_name")
    public String companyName;

    public VendorInvite withCompanyName(String companyName) {
        this.companyName = companyName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("company_phone")
    @SpeakeasyMetadata("form:name=company_phone multipartForm:name=company_phone")
    public String companyPhone;

    public VendorInvite withCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
        return this;
    }
    
    @JsonProperty("email")
    @SpeakeasyMetadata("form:name=email multipartForm:name=email")
    public String email;

    public VendorInvite withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("first_name")
    @SpeakeasyMetadata("form:name=first_name multipartForm:name=first_name")
    public String firstName;

    public VendorInvite withFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("last_name")
    @SpeakeasyMetadata("form:name=last_name multipartForm:name=last_name")
    public String lastName;

    public VendorInvite withLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("line_1")
    @SpeakeasyMetadata("form:name=line_1 multipartForm:name=line_1")
    public String line1;

    public VendorInvite withLine1(String line1) {
        this.line1 = line1;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("postcode")
    @SpeakeasyMetadata("form:name=postcode multipartForm:name=postcode")
    public String postcode;

    public VendorInvite withPostcode(String postcode) {
        this.postcode = postcode;
        return this;
    }
    
    public VendorInvite(@JsonProperty("email") String email) {
        this.email = email;
  }
}
