/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class WorkEntrySerializerList {
    @JsonProperty("agent")
    public Long agent;

    public WorkEntrySerializerList withAgent(Long agent) {
        this.agent = agent;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("checkin")
    public OffsetDateTime checkin;

    public WorkEntrySerializerList withCheckin(OffsetDateTime checkin) {
        this.checkin = checkin;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("checkout")
    public OffsetDateTime checkout;

    public WorkEntrySerializerList withCheckout(OffsetDateTime checkout) {
        this.checkout = checkout;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public WorkEntrySerializerList withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public WorkEntrySerializerList withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hours")
    public Float hours;

    public WorkEntrySerializerList withHours(Float hours) {
        this.hours = hours;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public WorkEntrySerializerList withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("long_description")
    public String longDescription;

    public WorkEntrySerializerList withLongDescription(String longDescription) {
        this.longDescription = longDescription;
        return this;
    }
    
    @JsonProperty("meld")
    public Long meld;

    public WorkEntrySerializerList withMeld(Long meld) {
        this.meld = meld;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public WorkEntrySerializerList withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    @JsonProperty("updater")
    public Long updater;

    public WorkEntrySerializerList withUpdater(Long updater) {
        this.updater = updater;
        return this;
    }
    
    public WorkEntrySerializerList(@JsonProperty("agent") Long agent, @JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("meld") Long meld, @JsonProperty("updated") OffsetDateTime updated, @JsonProperty("updater") Long updater) {
        this.agent = agent;
        this.created = created;
        this.id = id;
        this.meld = meld;
        this.updated = updated;
        this.updater = updater;
  }
}
