/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package PropertyMeld.MeldAPI.models.shared;

import PropertyMeld.MeldAPI.utils.DateTimeDeserializer;
import PropertyMeld.MeldAPI.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class WriteableTag {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("create_by")
    public java.util.Map<String, Object> createBy;

    public WriteableTag withCreateBy(java.util.Map<String, Object> createBy) {
        this.createBy = createBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created")
    public OffsetDateTime created;

    public WriteableTag withCreated(OffsetDateTime created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public WriteableTag withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("management")
    public Long management;

    public WriteableTag withManagement(Long management) {
        this.management = management;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public WriteableTag withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("update_by")
    public java.util.Map<String, Object> updateBy;

    public WriteableTag withUpdateBy(java.util.Map<String, Object> updateBy) {
        this.updateBy = updateBy;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("updated")
    public OffsetDateTime updated;

    public WriteableTag withUpdated(OffsetDateTime updated) {
        this.updated = updated;
        return this;
    }
    
    public WriteableTag(@JsonProperty("created") OffsetDateTime created, @JsonProperty("id") Long id, @JsonProperty("management") Long management, @JsonProperty("name") String name, @JsonProperty("updated") OffsetDateTime updated) {
        this.created = created;
        this.id = id;
        this.management = management;
        this.name = name;
        this.updated = updated;
  }
}
